### PR TITLE
Fix as_strided symint

### PR DESCRIPTION
**Pull request by antoniojkim**
Upstream PyTorch pushed out a change to `as_strided_copy` and `as_strided_scatter` for their Symbolic Integer effort. This caused a break in LTC.

Adding those ops to the symint list should fix things.

Also adding support for `hardtanh` to pass tests

https://github.com/llvm/torch-mlir/issues/1396

### CODE REVIEW

**Review by silvasean — APPROVED** [review]
Thanks for the quick fix!

**Comment by antoniojkim** [comment]
I built it locally and looked to see what op the error was happening for
```
/main_checkout/torch-mlir/build_oot/python/torch_mlir/csrc/base_lazy_backend/generated/LazyNativeFunctions.cpp:726
```
It happened to be `as_strided_copy` which lined up with this commit added yesterday to upstream PyTorch
https://github.com/pytorch/pytorch/commit/3eb27229dd74dd0bea434326c471f16c50e558a4

**Comment by antoniojkim** [comment]
> I built it locally and looked to see what op the error was happening for
> 
> ```
> /main_checkout/torch-mlir/build_oot/python/torch_mlir/csrc/base_lazy_backend/generated/LazyNativeFunctions.cpp:726
> ```
> 
> It happened to be `as_strided_copy` which lined up with this commit added yesterday to upstream PyTorch [pytorch/pytorch@3eb2722](https://github.com/pytorch/pytorch/commit/3eb27229dd74dd0bea434326c471f16c50e558a4)

And reading through that commit, they changed `as_strided_copy/scatter` to have symint support, so all we needed to do was make sure we were generating the symint versions of those ops too

**Comment by silvasean** [comment]
"e2e_testing.torchscript.main" should be "e2e_testing.main" to fix the python issue.

**Comment by dellis23** [comment]
Can we come up with a generally applicable flow for these situations?  I lean toward what Sean proposed of get the "rollback done" (though it's not exactly a rollback in this case) and then fix separately.

Is the worry that we might end up committing additional code while the LTC tests are disabled that would break LTC more and make fixing even worse?  Or would we also potentially generate releases that are broken for LTC?

**Comment by powderluv** [comment]
IMHO Revert first. Disable second. Fix third to get a tree green.

**Comment by powderluv** [comment]
@ashay yeah I think it is time to Pin Pytorch and roll only when tests pass. There is a tracker for it https://github.com/llvm/torch-mlir/issues/1328 . I had a WIP idea I will post in there to discuss and if you are willing to take over to land it please do.

**Comment by silvasean** [comment]
> @ashay yeah I think it is time to Pin Pytorch and roll only when tests pass. There is a tracker for it #1328 . I had a WIP idea I will post in there to discuss and if you are willing to take over to land it please do.

Yeah, I think that is a good idea. I've added a note to discuss this in the community meeting two weeks from now. We can discuss at the developer hour too.

**Comment by antoniojkim** [comment]
> I think it is time to Pin Pytorch and roll only when tests pass.

I'm in favour of this idea as well

**Pull request merged**
