### PR TITLE
[TOSA] Add LeakyReLU conversion pass

### PR DESCRIPTION
**Pull request by BraunPhilipp**

### CODE REVIEW

**Review by eric-k256 — APPROVED** [review]
looks good to me.

**Comment by BraunPhilipp** [comment]
@ashay @eric-k256 What needs to usually happen for these small PRs to get merged?

**Comment by ashay** [comment]
My apologies, looks like we dropped the ball here.  Generally, if you're a regular contributor, you'd have commit access to land the change yourself, but in the meantime, I (or someone else) can land this for you.

Sorry again, but since it's been 18 days since the last time this PR was rebased, would you mind rebasing it again please?  I'd be happy to do it myself, but that would make GitHub say that I am a co-author of this patch.  Once you rebase, I'll keep an eye on this PR and merge it soon after it passes all tests.

**Comment by eric-k256** [comment]
Yes, I'm sorry also. I failed to merge after the checks were run. I'll also keep an eye out for the rebase, and we'll get it in.

**Comment by BraunPhilipp** [comment]
@eric-k256 @ashay Happy New Year 🥳 

Now, I also forgot about this issue so no worries. Hope rebase was correct and we can merge `LeakyReLU` support.

**Comment by ashay** [comment]
Hi @BraunPhilipp!  Happy new year to you as well.

Thanks for rebasing, but it looks like you missed switching to the prefixed accessors in a couple of places [https://github.com/llvm/torch-mlir/actions/runs/3821124291/jobs/6504277585#step:7:4926].

**Comment by ashay** [comment]
Closing in favor of https://github.com/llvm/torch-mlir/pull/1790, which rebases the changes on top of the LLVM tag update.  Philipp, as I understand, the commit should still be attributed to you, although the PR might say that it was co-authored by you and me.

**Comment by BraunPhilipp** [comment]
Appreciate it, it was getting late yesterday and building took a while 😄

**Pull request closed without merging**
