### PR TITLE
Disable LTC again

### PR DESCRIPTION
**Pull request by silvasean**
https://github.com/llvm/torch-mlir/issues/1396

### CODE REVIEW

**Review by fortianyou — APPROVED** [review]
LGTM, thanks @silvasean

**Review by dellis23 — APPROVED** [review]

**Comment by dellis23** [comment]
Thanks!

**Comment by antoniojkim** [comment]
I would very highly prefer that we fix the issue instead of just disabling LTC again. I have a PR up to fix the issue here
https://github.com/llvm/torch-mlir/pull/1401

**Comment by silvasean** [comment]
Great! Thanks for the quick fix.

The general feeling in LLVM community development is to get HEAD back to a green state as fast as possible, rather than waiting for "fixing forward". See e.g. our patch reversion policy https://llvm.org/docs/DeveloperPolicy.html#patch-reversion-policy
In this case, it's awesome that we were able to get a fix so quickly, however in my experience usually these things can take longer, so it's always "safe" to go back to green and generally preferable to get HEAD green again immediately.

**Pull request closed without merging**
