### PR TITLE
Reject dictionary inputs when tracing.

### PR DESCRIPTION
**Pull request by dellis23**
The underlying error message was misleading.  See https://github.com/llvm/torch-mlir/issues/1425

### CODE REVIEW

**Comment by dellis23** [comment]
One question: is it safe to have an allowlist that only allows `Tensor` and `TensorPlaceholder`?  If so, I figured this approach would be more flexible and easier to maintain.

**Comment by ramiro050** [comment]
> One question: is it safe to have an allowlist that only allows `Tensor` and `TensorPlaceholder`? If so, I figured this approach would be more flexible and easier to maintain.

Yeah, I think it would be better to throw an error in the beginning of the function if `example_inputs` doesn't match the type `Union[_example_arg, Sequence[_example_arg]]`, rather than having special handling for `dict`s. 

You can check if something is a `Sequence` by doing:

```python
from collections.abc import Sequence

if not isinstance(example_args, Sequence):
    raise ...
```

**Comment by dellis23** [comment]
Okay, I've updated it.  Unfortunately, doing it this way means we have to do the check in a couple of places, since we allow both sequences and non-sequences as inputs.

**Review by ramiro050 — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
