### PR TITLE
Revert "update PyTorch version to 2.1.0.dev20230430"

### PR DESCRIPTION
**Pull request by ramiro050**
This reverts commit eab1930c491d0a59cc0467f0091f5a05f9d2bd60.

The PyTorch version does not yet exist for MacOS.

### CODE REVIEW

**Comment by makslevental** [comment]
Can we just disable this thing? Or at least gate it by whether things successfully compile after the roll?

**Review by makslevental — APPROVED** [review]
Can we just disable this thing? Or at least gate it by whether things successfully compile after the roll?

**Review by powderluv — APPROVED** [review]

**Comment by powderluv** [comment]
yeah we should check for mac builds also before roll. @ashay should we just add the normal macos test ?

**Comment by ramiro050** [comment]
The MacOS build will take (from looking at the current pace) around 2 more hours to finish. However, this PR should pass all the builds, since this is reverting the latest commit on main and the previous commit is green. I will go ahead and merge early to unblock people.

**Comment by ashay** [comment]
> should we just add the normal macos test ?

Yes, this seems to be a recurring issue, so I'll add macOS to the list of tested platforms.  I'll try to get this out this week.

**Pull request merged**
