### PR TITLE
update llvm & mlir

### PR DESCRIPTION
**Pull request by qiuxiafei**

### CODE REVIEW

**Comment by ramiro050** [comment]
@ashay @powderluv, any idea what could be causing the MacOS CI failure?

**Comment by powderluv** [comment]
I'm without proper connectivity till Tuesday to take a look. @stellaraccident  in case she has any idea. Looks like an upstream LLVM dependency ?

**Comment by ashay** [comment]
Like Anush said, this could be because of an upstream bug (it seems like a patch to mlir/test/CMakeLists.txt was reverted the same day, but our chosen commit doesn't include the revert).

In picking the LLVM green commit each week, we run Windows and Linux builds but not macOS builds, which probably caused a bad commit to slip.  I'll add macOS to our green commit builds so that we don't run into problems like this in the future.

**Comment by ramiro050** [comment]
> I'll add macOS to our green commit builds so that we don't run into problems like this in the future.

Thanks!

**Comment by ashay** [comment]
Closing because we have merged LLVM after this PR was created.

**Pull request closed without merging**
