### PR TITLE
[MLIR][TORCH] Add E2E support for aten.index_put.hacked_twin op

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
This commit decomposes `aten.index_put.hacked_twin` op into
`valsem.aten.index_put_impl` op.

Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
Hi, I am getting the following error while running the e2e test:
```
FAIL - "IndexPutHackedTwinOneDimFloatNonAccumulateModule_basic"

Unexpected outcome summary:

****** Failed tests - 1 tests
    FAIL - "IndexPutHackedTwinOneDimFloatNonAccumulateModule_basic"
        Compilation error: Traceback (most recent call last):
          File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/torchscript/framework.py", line 302, in run_tests
            golden_trace = generate_golden_trace(test)
          File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/torchscript/framework.py", line 292, in generate_golden_trace
            test.program_invoker(tracer, TestUtils())
          File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/e2e_testing/torchscript/index_put.py", line 222, in IndexPutHackedTwinOneDimFloatNonAccumulateModule_basic
            module.forward(tu.rand(100), torch.randint(100, (250,)),
          File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/torchscript/framework.py", line 272, in __call__
            output = self.__wrapped__(*args, **kwargs)
          File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/e2e_testing/torchscript/index_put.py", line 217, in forward
            return torch.ops.aten.index_put.hacked_twin(input, [index], value, accumulate=False)
          File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_ops.py", line 48, in __call__
            return self._op(*args, **kwargs or {})
        RuntimeError: Tried to cast a List<Tensor> to a List<Tensor?>. Types mismatch.


Summary:
    Failed: 1
```

**Comment by ramiro050** [comment]
I think the error is in PyTorch. In the signature for that function, the argument is specified as `Tensor[]`, but then it gets casted into a `c10::List<c10::optional<at::Tensor>>`:

https://github.com/pytorch/pytorch/blob/3024bcfff5c5e497b602063dc2d948a4d4c10155/torch/csrc/jit/runtime/register_prim_ops.cpp#L1026

Also, this seems to be some obscure code in PyTorch (https://github.com/pytorch/pytorch/blob/3024bcfff5c5e497b602063dc2d948a4d4c10155/torch/csrc/jit/runtime/register_prim_ops.cpp#L982). As far as I can tell, this op is not unit tested by PyTorch, so they might be unaware that it doesn't work.

**Comment by vivekkhandelwal1** [comment]
> I think the error is in PyTorch. In the signature for that function, the argument is specified as `Tensor[]`, but then it gets casted into a `c10::List<c10::optional<at::Tensor>>`:
> 
> https://github.com/pytorch/pytorch/blob/3024bcfff5c5e497b602063dc2d948a4d4c10155/torch/csrc/jit/runtime/register_prim_ops.cpp#L1026
> 
> Also, this seems to be some obscure code in PyTorch (https://github.com/pytorch/pytorch/blob/3024bcfff5c5e497b602063dc2d948a4d4c10155/torch/csrc/jit/runtime/register_prim_ops.cpp#L982). As far as I can tell, this op is not unit tested by PyTorch, so they might be unaware that it doesn't work.

What should we do as of now? Remove the test case?

**Comment by silvasean** [comment]
> I think the error is in PyTorch. In the signature for that function, the argument is specified as `Tensor[]`, but then it gets casted into a `c10::List<c10::optional<at::Tensor>>`:
> 
> https://github.com/pytorch/pytorch/blob/3024bcfff5c5e497b602063dc2d948a4d4c10155/torch/csrc/jit/runtime/register_prim_ops.cpp#L1026
> 
> Also, this seems to be some obscure code in PyTorch (https://github.com/pytorch/pytorch/blob/3024bcfff5c5e497b602063dc2d948a4d4c10155/torch/csrc/jit/runtime/register_prim_ops.cpp#L982). As far as I can tell, this op is not unit tested by PyTorch, so they might be unaware that it doesn't work.

But the op /does/ run correctly within the real model, right?

I think we want to do two things here:

1. Be good community citizens and create an upstream bug for this, so that PT devs are aware of it.
2. We need at least one test case that runs e2e. I think we need to investigate how this op is invoked in the real model and make sure that we are invoking it in the same way.

**Comment by ramiro050** [comment]
> But the op /does/ run correctly within the real model, right?

I just found something interesting. The real model does run correctly because it does *not* use the `hacked_twin` variant; it uses the regular `aten.index_put`. The issue seems to be on our side when we import the TorchScript graph. The importer gets confused because the `hacked_twin` variant has the signature `(Tensor, Tensor[], Tensor, bool, bool) -> (Tensor)` while the regular `index_put` has the signature `(Tensor, Tensor?[], Tensor, bool) -> (Tensor)`, which is less precise in the second argument.

If I run the `forward` method

```python
def forward(self, a):
    return torch.ops.aten.index_put(a, [torch.tensor(0), None], torch.tensor(0), False)
```

I get the TorchScript below, which 

```
graph(%self : __torch__.MyModule,
      %a.1 : Tensor):
  %6 : bool = prim::Constant[value=0]()
  %4 : NoneType = prim::Constant()
  %3 : int = prim::Constant[value=0]() # /home/ramiroleal/aot-torch-mlir/torch-mlir/../torch-mlir-scripts/torchscript_to_linalg.py:27:57
  %7 : Tensor = aten::tensor(%3, %4, %4, %6) # /home/ramiroleal/aot-torch-mlir/torch-mlir/../torch-mlir-scripts/torchscript_to_linalg.py:27:44
  %9 : Tensor?[] = prim::ListConstruct(%7, %4)
  %13 : Tensor = aten::tensor(%3, %4, %4, %6) # /home/ramiroleal/aot-torch-mlir/torch-mlir/../torch-mlir-scripts/torchscript_to_linalg.py:27:68
  %15 : Tensor = aten::index_put(%a.1, %9, %13, %6) # /home/ramiroleal/aot-torch-mlir/torch-mlir/../torch-mlir-scripts/torchscript_to_linalg.py:27:15
  return (%15)
```

and the `torch-mlir` uses the regular `aten.index_put` because the second argument is `Tensor?[]`:

```mlir
  func private @__torch__.MyModule.forward(%arg0: !torch.nn.Module<"__torch__.MyModule">, %arg1: !torch.tensor {torch.type_bound = !torch.vtensor<[?,?],si32>}) -> !torch.tensor {
    %false = torch.constant.bool false
    %none_0 = torch.constant.none
    %int0 = torch.constant.int 0
    %1 = torch.aten.tensor.int %int0, %none_0, %none_0, %false : !torch.int, !torch.none, !torch.none, !torch.bool -> !torch.tensor
    %2 = torch.prim.ListConstruct %1, %none_0 : (!torch.tensor, !torch.none) -> !torch.list<optional<tensor>>
    %3 = torch.aten.tensor.int %int0, %none_0, %none_0, %false : !torch.int, !torch.none, !torch.none, !torch.bool -> !torch.tensor
    %4 = torch.aten.index_put %arg1, %2, %3, %false : !torch.tensor, !torch.list<optional<tensor>>, !torch.tensor, !torch.bool -> !torch.tensor
    return %4 : !torch.tensor
  }
```

However, if I run 

```python
def forward(self, a):
    return torch.ops.aten.index_put(a, [torch.tensor(0)], torch.tensor(0), False)
```

I get the TorchScript

```
graph(%self : __torch__.MyModule,
      %a.1 : Tensor):
  %6 : bool = prim::Constant[value=0]()
  %4 : NoneType = prim::Constant()
  %3 : int = prim::Constant[value=0]() # /home/ramiroleal/aot-torch-mlir/torch-mlir/../torch-mlir-scripts/torchscript_to_linalg.py:27:57
  %7 : Tensor = aten::tensor(%3, %4, %4, %6) # /home/ramiroleal/aot-torch-mlir/torch-mlir/../torch-mlir-scripts/torchscript_to_linalg.py:27:44
  %8 : Tensor[] = prim::ListConstruct(%7)
  %12 : Tensor = aten::tensor(%3, %4, %4, %6) # /home/ramiroleal/aot-torch-mlir/torch-mlir/../torch-mlir-scripts/torchscript_to_linalg.py:27:62
  %14 : Tensor = aten::index_put(%a.1, %8, %12, %6) # /home/ramiroleal/aot-torch-mlir/torch-mlir/../torch-mlir-scripts/torchscript_to_linalg.py:27:15
  return (%14)
```

which identifies the second argument as `Tensor[]`, so the importer chooses the hacked variant:

```mlir
  func private @__torch__.MyModule.forward(%arg0: !torch.nn.Module<"__torch__.MyModule">, %arg1: !torch.tensor {torch.type_bound = !torch.vtensor<[?,?],si32>}) -> !torch.tensor {
    %false = torch.constant.bool false
    %none_0 = torch.constant.none
    %int0 = torch.constant.int 0
    %1 = torch.aten.tensor.int %int0, %none_0, %none_0, %false : !torch.int, !torch.none, !torch.none, !torch.bool -> !torch.tensor
    %2 = torch.prim.ListConstruct %1 : (!torch.tensor) -> !torch.list<tensor>
    %3 = torch.aten.tensor.int %int0, %none_0, %none_0, %false : !torch.int, !torch.none, !torch.none, !torch.bool -> !torch.tensor
    %4 = torch.operator "aten.index_put.hacked_twin"(%arg1, %2, %3, %false) : (!torch.tensor, !torch.list<tensor>, !torch.tensor, !torch.bool) -> !torch.tensor
    return %4 : !torch.tensor
  }
```

**Comment by vivekkhandelwal1** [comment]
Hi, @silvasean @ramiro050. I have created a bug (https://github.com/pytorch/pytorch/issues/75015) for the inconsistency with the `aten::index_put.hacked_twin` op. Now, I should wait for the bug to get fixed, right?

**Comment by silvasean** [comment]
> Hi, @silvasean @ramiro050. I have created a bug ([pytorch/pytorch#75015](https://github.com/pytorch/pytorch/issues/75015)) for the inconsistency with the `aten::index_put.hacked_twin` op. Now, I should wait for the bug to get fixed, right?

Yeah, I think we should wait (and ping the bug / reach out to folks to get it fixed, if this is blocking us).

**Comment by vivekkhandelwal1** [comment]
@cathyzhyi @silvasean, please review this PR.

**Review by cathyzhyi — APPROVED** [review]
Looks good. Can you help to add `# ========` between test cases in this file. 
Also, can you add a comment saying `IndexPutHackedTwin` tests are using the `aten.index_put.hacked_twin` operator.

**Pull request merged**
