### PR TITLE
Add clang-format check to CI

### PR DESCRIPTION
**Pull request by ramiro050**
This PR adds a check to the CI right after checking out the Torch-MLIR repository to make sure that the changes in the PR don't require any `git clang-format` modifications.

### CODE REVIEW

**Comment by ramiro050** [comment]
See CI error for unformatted code:

https://github.com/llvm/torch-mlir/actions/runs/7674955115/job/20920465785?pr=2816

**Comment by ramiro050** [comment]
I don't have much experience with Github actions, so let me know if I'm doing something terribly wrong 🙂

**Review by qedawkins — APPROVED** [review]
LGTM! I don't have any experience either though

**Comment by stellaraccident** [comment]
Over the weekend, I switched us off of buildAndTest (to ci.yml). I created a dedicated lint pipeline. Should be trivial to add there: https://github.com/llvm/torch-mlir/blob/main/.github/workflows/lint.yml

**Comment by ramiro050** [comment]
Tested in: https://github.com/llvm/torch-mlir/actions/runs/7704691113/job/20997426024

PTAL.

**Review by stellaraccident — APPROVED** [review]
Thanks much

**Pull request merged**
