### PR TITLE
[Stablehlo] Add `AtenIndexTensor` StableHlo support

### PR DESCRIPTION
**Pull request by zhekunz2**

### CODE REVIEW

**Comment by AmosLewis** [comment]
@zhekunz2  This patch looks good to me. I have tested it in OPT model. Could you clean this patch and merge all the commits into one? I will need this patch in https://github.com/nod-ai/SHARK/issues/1441.

**Review by AmosLewis — CHANGES_REQUESTED** [review]
@zhekunz2 This patch looks good to me. I have tested it in OPT model. Could you clean this patch and merge all the commits into one? I will need this patch in https://github.com/nod-ai/SHARK/issues/1441.

**Comment by ZihengJiang** [comment]
> @zhekunz2 This patch looks good to me. I have tested it in OPT model. Could you clean this patch and merge all 8 commits into one? I will need this patch in [nod-ai/SHARK#1441](https://github.com/nod-ai/SHARK/issues/1441).

Hi @AmosLewis , usually those commits will be squashed during merging.

If you don't have further opinion, I can merge it

**Comment by AmosLewis** [comment]
> > @zhekunz2 This patch looks good to me. I have tested it in OPT model. Could you clean this patch and merge all 8 commits into one? I will need this patch in [nod-ai/SHARK#1441](https://github.com/nod-ai/SHARK/issues/1441).
> 
> Hi @AmosLewis , usually those commits will be squashed during merging.
> 
> If you don't have further opinion, I can merge it

Yes. Just merged it. Thanks.

**Review by AmosLewis — APPROVED** [review]

**Pull request merged**
