### PR TITLE
[NFC] Rename external -> externals

### PR DESCRIPTION
**Pull request by asaadaldien**
This resolves issues with bazel top level [`external`](https://github.com/bazelbuild/bazel/issues/4508) directory.

Towards fixing #14

### CODE REVIEW

**Comment by silvasean** [comment]
Can you squash the commits and link to the bug from the commit message?

**Comment by asaadaldien** [comment]
@silvasean done, PTAL. thanks!

**Review by silvasean — APPROVED** [review]
nit: can you also link to the Torch-MLIR bug as well from the PR description?

Also, do we need any special git flags when syncing past this PR?

**Comment by asaadaldien** [comment]
> nit: can you also link to the Torch-MLIR bug as well from the PR description?
> 
> Also, do we need any special git flags when syncing past this PR?

Not git but cmake, should I update README in this PR ? to do:
```
cmake -GNinja -Bbuild \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DPython3_FIND_VIRTUALENV=ONLY \
  -DLLVM_ENABLE_PROJECTS=mlir \
  -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects" \
  -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=`pwd` \
  -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=`pwd`/external/llvm-external-projects/torch-mlir-dialects \
  -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
  -DLLVM_TARGETS_TO_BUILD=host \
  externals/llvm-project/llvm
  ```

**Comment by silvasean** [comment]
Yes, please update everything in the repo that references the old name atomically in this PR.

You should have push ability on the repo, so feel free to push when you are satisfied.

**Pull request merged**
