### PR TITLE
[ONNX] Fix resize ceil numerics and add half_pixel_symmetric support

### PR DESCRIPTION
**Pull request by zjgarvey**
This patch fixes several failing tests in our [external test suite](https://github.com/nod-ai/SHARK-TestSuite/tree/main/iree_tests/onnx/node/generated), and addresses some of the issues discussed in #3420

### CODE REVIEW

**Comment by mgehre-amd** [comment]
> This patch fixes several failing tests in our [external test suite](https://github.com/nod-ai/SHARK-TestSuite/tree/main/iree_tests/onnx/node/generated?rgh-link-date=2024-06-10T14%3A58%3A03Z), and addresses some of the issues discussed in #3420

Curious, I found https://github.com/nod-ai/e2eshark-reports/blob/main/2024-06-10/onnx_reports/statusreport.md but I cannot find a corresponding report for that external test suite (essentially per op). Is that available?

**Comment by zjgarvey** [comment]
I was testing locally a build of iree with this torch-mlir commit. IREE's ci runs the onnx node tests, so when we bump torch-mlir there, we should get a few more passes. Here is an example of an [IREE Regression Test](https://github.com/iree-org/iree/actions/runs/9351486214/job/25737852399#step:8:697)

**Comment by zjgarvey** [comment]
> > This patch fixes several failing tests in our [external test suite](https://github.com/nod-ai/SHARK-TestSuite/tree/main/iree_tests/onnx/node/generated?rgh-link-date=2024-06-10T14%3A58%3A03Z), and addresses some of the issues discussed in #3420
> 
> Curious, I found https://github.com/nod-ai/e2eshark-reports/blob/main/2024-06-10/onnx_reports/statusreport.md but I cannot find a corresponding report for that external test suite (essentially per op). Is that available?

I forgot to quote the reply, sorry about that. In any case, I merged the work you committed earlier today, @mgehre-amd. Would you mind reviewing this PR?

**Comment by zjgarvey** [comment]
There is also a [tracking issue for ONNX Frontend Support](https://github.com/nod-ai/SHARK-Turbine/issues/564) that you can check out if you want to contribute towards this project.

**Review by mgehre-amd — APPROVED** [review]
Thanks! The implementation looks correct. Can you please add a test for it?

**Review by mgehre-amd — COMMENTED** [review]
Waiting for test

**Pull request merged**
