### PR TITLE
Update llvm for tensor collapse/expand

### PR DESCRIPTION
**Pull request by dan-garvey**
EDIT: updates llvm to: d3208cf1cdc927e5e74f6f6a1a69dc548ac629e0

### CODE REVIEW

**Comment by cathyzhyi** [comment]
Thanks for this change. I think we need to use the sha from upstream repo for the submodule sha. We might alos need to add some more fixes. I am trying in my local repo.

**Comment by cathyzhyi** [comment]
Here are some more fixes https://github.com/cathyzhyi/mlir-npcomp/commit/2eff10f9254f7e03ea0d5fefe39778c59b8e9ae1

**Comment by cathyzhyi** [comment]
FYI, the asm printer is also broken by https://reviews.llvm.org/D113873

**Comment by dan-garvey** [comment]
> FYI, the asm printer is also broken by https://reviews.llvm.org/D113873

I'll take a look

**Comment by cathyzhyi** [comment]
After some discussion with MLIR folks, people are proposing to add options to revert https://reviews.llvm.org/D113873. This change makes
```
%0 = torch.aten.size %arg0 : !torch.vtensor<[?,3],f32> -> !torch.list<!torch.int>
```
becomes
```
%0 = torch.aten.size %arg0 : !torch.vtensor<[?,3],f32> -> <!torch.int>
```
which affects the readability.
The author of the change would be back next week so I would suggest we hold off the change for now if it's not too urgent.

**Comment by cathyzhyi** [comment]
FYI, this is the [fix](https://reviews.llvm.org/D116905) for the printer failures.

**Comment by cathyzhyi** [comment]
@dan-garvey I will take this one as it's needed for https://github.com/llvm/torch-mlir/pull/528

**Comment by cathyzhyi** [comment]
closing as it's covered by #529

**Pull request closed without merging**
