### PR TITLE
Include Bazel BUILD steps to development.md

### PR DESCRIPTION
**Pull request by sjain-stanford**
Make the bazel build a little more visible to potential users.

cc: @asaadaldien

### CODE REVIEW

**Comment by jpienaar** [comment]
Thanks for highlighting this, OOC why add this to the readme rather than development.md alongside the cmake instructions?

**Comment by sjain-stanford** [comment]
> why add this to the readme rather than development.md alongside the cmake instructions?

Thanks for the pointer. I've moved the build instructions to `development.md`. I think the rest of the instructions there are closely tied to the CMake build (e.g. testing, virtualenv setup). I'll send some follow-up PRs to include LIT tests + E2E integration tests using bazel. At that point it may be better to re-factor this file with specific steps (for CMake vs Bazel). @jpienaar WDYT?

**Comment by silvasean** [comment]
This is awesome!

@asaadaldien for review + merging

**Review by asaadaldien — COMMENTED** [review]
LGTM!

**Pull request merged**
