### PR TITLE
Bump stablehlo to openxla/stablehlo@fd52182f76cadb82f2064fe5fc49a4fb4347a826

### PR DESCRIPTION
**Pull request by sjain-stanford**
With the recent LLVM integrate and changes from https://github.com/llvm/llvm-project/pull/78260, we hit this build error in Stablehlo (which is quite old). 
```
external/stablehlo/stablehlo/transforms/StablehloRefineShapes.cpp:1020:14: error: no member named 'startRootUpdate' in 'mlir::PatternRewriter'
    rewriter.startRootUpdate(op);
    ~~~~~~~~ ^
external/stablehlo/stablehlo/transforms/StablehloRefineShapes.cpp:1026:16: error: no member named 'finalizeRootUpdate' in 'mlir::PatternRewriter'
      rewriter.finalizeRootUpdate(op);
      ~~~~~~~~ ^
external/stablehlo/stablehlo/transforms/StablehloRefineShapes.cpp:1029:16: error: no member named 'cancelRootUpdate' in 'mlir::PatternRewriter'
      rewriter.cancelRootUpdate(op);
      ~~~~~~~~ ^
external/stablehlo/stablehlo/transforms/StablehloRefineShapes.cpp:1108:14: error: no member named 'updateRootInPlace' in 'mlir::PatternRewriter'
    rewriter.updateRootInPlace(op->getParentOp(), [&]() { return; });
    ~~~~~~~~ ^
4 errors generated.
Target @torch-mlir//:torch-mlir-opt failed to build
```

I'm still puzzled as to how this didn't fail with the CMake merge gating CI (do we not test Stablehlo builds/tests?). In any case, bumping our submodule to https://github.com/openxla/stablehlo/pull/1918 fixes it. 

It exposes a new failing lit test in TorchToStablehlo though, that I have looped stablehlo developers into ([here](https://discord.com/channels/999073994483433573/999074539138990131/1201235845391331419)).
```
bazel run @torch-mlir//test/Conversion:TorchToStablehlo/scatter.mlir.test 

...external/torch-mlir/test/Conversion/TorchToStablehlo/scatter.mlir
within split at <stdin>:1 offset :33:8: error: unexpected error: Expects non-empty reduction block for type inference                                                                               
  %0 = torch.aten.scatter.src %arg0, %int0, %arg1, %arg2 : !torch.vtensor<[?,?],si64>, !torch.int, !torch.vtensor<[?,?],si64>, !torch.vtensor<[?,?],si64> -> !torch.vtensor<[?,?],si64>             
       ^                                                                                                                                                                                            
LLVM ERROR: Failed to infer result type(s).               
```

Bazel CI: https://github.com/sjain-stanford/torch-mlir/actions/runs/7732673480/job/21083102228

### CODE REVIEW

**Comment by stellaraccident** [comment]
> With the recent LLVM integrate and changes from [llvm/llvm-project#78260](https://github.com/llvm/llvm-project/pull/78260), we hit this build error in Stablehlo (which is quite old).
> 
> ```
> external/stablehlo/stablehlo/transforms/StablehloRefineShapes.cpp:1020:14: error: no member named 'startRootUpdate' in 'mlir::PatternRewriter'
>     rewriter.startRootUpdate(op);
>     ~~~~~~~~ ^
> external/stablehlo/stablehlo/transforms/StablehloRefineShapes.cpp:1026:16: error: no member named 'finalizeRootUpdate' in 'mlir::PatternRewriter'
>       rewriter.finalizeRootUpdate(op);
>       ~~~~~~~~ ^
> external/stablehlo/stablehlo/transforms/StablehloRefineShapes.cpp:1029:16: error: no member named 'cancelRootUpdate' in 'mlir::PatternRewriter'
>       rewriter.cancelRootUpdate(op);
>       ~~~~~~~~ ^
> external/stablehlo/stablehlo/transforms/StablehloRefineShapes.cpp:1108:14: error: no member named 'updateRootInPlace' in 'mlir::PatternRewriter'
>     rewriter.updateRootInPlace(op->getParentOp(), [&]() { return; });
>     ~~~~~~~~ ^
> 4 errors generated.
> Target @torch-mlir//:torch-mlir-opt failed to build
> ```
> 
> I'm still puzzled as to how this didn't fail with the CMake merge gating CI (do we not test Stablehlo builds/tests?). In any case, bumping our submodule to [openxla/stablehlo#1918](https://github.com/openxla/stablehlo/pull/1918) fixes it.
> 
> It exposes a new failing lit test in TorchToStablehlo though, that I have looped stablehlo developers into ([here](https://discord.com/channels/999073994483433573/999074539138990131/1201235845391331419)).
> 
> ```
> bazel run @torch-mlir//test/Conversion:TorchToStablehlo/scatter.mlir.test 
> 
> ...external/torch-mlir/test/Conversion/TorchToStablehlo/scatter.mlir
> within split at <stdin>:1 offset :33:8: error: unexpected error: Expects non-empty reduction block for type inference                                                                               
>   %0 = torch.aten.scatter.src %arg0, %int0, %arg1, %arg2 : !torch.vtensor<[?,?],si64>, !torch.int, !torch.vtensor<[?,?],si64>, !torch.vtensor<[?,?],si64> -> !torch.vtensor<[?,?],si64>             
>        ^                                                                                                                                                                                            
> LLVM ERROR: Failed to infer result type(s).               
> ```
> 
> Bazel CI: https://github.com/sjain-stanford/torch-mlir/actions/runs/7687378424/job/20947325658

I often found it hard to figure out what the old CI was testing. Looks like the new one gets it, so focused there.

**Comment by sjain-stanford** [comment]
A lot more conversions needed an update, I think this is all of it: https://github.com/llvm/torch-mlir/commit/a0ad9a83254bad7371b3164c93ce2ae17f1791f7. The bazel build works, I have one lit test that needs an update. 

The CMake build now [fails](https://github.com/llvm/torch-mlir/actions/runs/7729517677/job/21072878412?pr=2821) with setup_sanitizers. Probably related to https://github.com/openxla/stablehlo/pull/1959 (cc: @fzakaria , @mlevesquedion, @sdasgup3  ). I see the default for `STABLEHLO_ENABLE_SANITIZER` being `OFF`, but this code probably needs to be enclosed in an `if-endif`:
```
include(SetupSanitizers)
setup_sanitizers()
```
Error:
```
  -- Building StableHLO as an external LLVM project
  -- Building with -fPIC
  CMake Error at /_work/torch-mlir/torch-mlir/externals/stablehlo/CMakeLists.txt:147 (include):
    include could not find requested file:
  
      SetupSanitizers
  
  
  CMake Error at /_work/torch-mlir/torch-mlir/externals/stablehlo/CMakeLists.txt:148 (setup_sanitizers):
    Unknown CMake command "setup_sanitizers".
  
  
  -- Configuring incomplete, errors occurred!
```

**Comment by sjain-stanford** [comment]
Picked up patch: https://github.com/openxla/stablehlo/pull/1972

**Review by stellaraccident — APPROVED** [review]
Thank you for the community service.

**Pull request merged**
