### PR TITLE
Fix cache-suffix name bug

### PR DESCRIPTION
**Pull request by powderluv**
This should enabling better caching of builds.

### CODE REVIEW

**Review by makslevental — COMMENTED** [review]
LGTM

**Comment by powderluv** [comment]
Do you know what would cause 
```
PASS - "_SoftmaxModule_basic"

Unexpected outcome summary:

****** Failed tests - 1 tests
    FAIL - "Matmul_vecmat"
        @ trace item #0 - call to "forward"
        @ output of call to "forward"
        ERROR: shape (torch.Size([1, 5])) is not equal to golden shape (torch.Size([5]))


Summary:
    Passed: 653
    Failed: 1
```

In the eager mode tests ?

**Comment by makslevental** [comment]
> Do you know what would cause
> 
> ```
> PASS - "_SoftmaxModule_basic"
> 
> Unexpected outcome summary:
> 
> ****** Failed tests - 1 tests
>     FAIL - "Matmul_vecmat"
>         @ trace item #0 - call to "forward"
>         @ output of call to "forward"
>         ERROR: shape (torch.Size([1, 5])) is not equal to golden shape (torch.Size([5]))
> 
> 
> Summary:
>     Passed: 653
>     Failed: 1
> ```
> In the eager mode tests ?

@powderluv 

I expect some type system shenanigans symbolic trace sees a `d` element vector but it actually gets turned into a `1*d` matrix for this particular op. Will take a look soon.

**Comment by powderluv** [comment]
CI fix has landed on master.

**Pull request merged**
