### PR TITLE
[MLIR][TORCH] Add support for aten._unsafe_index_put.hacked_twin op

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
The CI failure is because of the stable torch not containing those op changes.

**Review by ramiro050 — APPROVED** [review]
LGTM! If you rebase, the stable CI should no longer be required to pass in order to merge

**Comment by bailuan** [comment]
Hi, @vivekkhandelwal1. 
I encountered the same issue when I tried to convert llama2 model:
`iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline:
error: unknown: failed to legalize operation 'torch.operator' that was explicitly marked illegal
 note: unknown: see current operation: %1251 = "torch.operator"(%1249, %1250, %1247, %13) <{name = "torch.aten._unsafe_index_put"}> : (!torch.vtensor<[32000,288],f32>, !torch.list<optional<vtensor>>, !torch.vtensor<[1,256,288],f32>, !torch.bool) -> !torch.vtensor<[32000,288],f32>`
could you tell me the version of your torch? I saw the method within "unsafe_index_put" in my torch 2.1.0 is :
`namespace at {
namespace native {
TORCH_API at::Tensor _unsafe_index_put(const at::Tensor & self, const c10::List<c10::optional<at::Tensor>> & indices, const at::Tensor & values, bool accumulate=false);
} // namespace native
} // namespace at` 
where is the ".hacked_twin.op"? why not take a change on _unsafe_index_put?
looking for your reply. Thanks a lot!

**Comment by vivekkhandelwal1** [comment]
> Hi, @vivekkhandelwal1. I encountered the same issue when I tried to convert llama2 model: `iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline: error: unknown: failed to legalize operation 'torch.operator' that was explicitly marked illegal note: unknown: see current operation: %1251 = "torch.operator"(%1249, %1250, %1247, %13) <{name = "torch.aten._unsafe_index_put"}> : (!torch.vtensor<[32000,288],f32>, !torch.list<optional<vtensor>>, !torch.vtensor<[1,256,288],f32>, !torch.bool) -> !torch.vtensor<[32000,288],f32>` could you tell me the version of your torch? I saw the method within "unsafe_index_put" in my torch 2.1.0 is : `namespace at { namespace native { TORCH_API at::Tensor _unsafe_index_put(const at::Tensor & self, const c10::List<c10::optional<at::Tensor>> & indices, const at::Tensor & values, bool accumulate=false); } // namespace native } // namespace at` where is the ".hacked_twin.op"? why not take a change on _unsafe_index_put? looking for your reply. Thanks a lot!

The error you got is because torch-mlir does not contain lowering for `torch.aten._unsafe_index_put` op.

**Comment by bailuan** [comment]
> > Hi, @vivekkhandelwal1. I encountered the same issue when I tried to convert llama2 model: `iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline: error: unknown: failed to legalize operation 'torch.operator' that was explicitly marked illegal note: unknown: see current operation: %1251 = "torch.operator"(%1249, %1250, %1247, %13) <{name = "torch.aten._unsafe_index_put"}> : (!torch.vtensor<[32000,288],f32>, !torch.list<optional<vtensor>>, !torch.vtensor<[1,256,288],f32>, !torch.bool) -> !torch.vtensor<[32000,288],f32>` could you tell me the version of your torch? I saw the method within "unsafe_index_put" in my torch 2.1.0 is : `namespace at { namespace native { TORCH_API at::Tensor _unsafe_index_put(const at::Tensor & self, const c10::List<c10::optional<at::Tensor>> & indices, const at::Tensor & values, bool accumulate=false); } // namespace native } // namespace at` where is the ".hacked_twin.op"? why not take a change on _unsafe_index_put? looking for your reply. Thanks a lot!
> 
> The error you got is because torch-mlir does not contain lowering for `torch.aten._unsafe_index_put` op.

Thanks for your quick reply, could you give some advice to process the issue?

**Comment by vivekkhandelwal1** [comment]
> > > Hi, @vivekkhandelwal1. I encountered the same issue when I tried to convert llama2 model: `iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline: error: unknown: failed to legalize operation 'torch.operator' that was explicitly marked illegal note: unknown: see current operation: %1251 = "torch.operator"(%1249, %1250, %1247, %13) <{name = "torch.aten._unsafe_index_put"}> : (!torch.vtensor<[32000,288],f32>, !torch.list<optional<vtensor>>, !torch.vtensor<[1,256,288],f32>, !torch.bool) -> !torch.vtensor<[32000,288],f32>` could you tell me the version of your torch? I saw the method within "unsafe_index_put" in my torch 2.1.0 is : `namespace at { namespace native { TORCH_API at::Tensor _unsafe_index_put(const at::Tensor & self, const c10::List<c10::optional<at::Tensor>> & indices, const at::Tensor & values, bool accumulate=false); } // namespace native } // namespace at` where is the ".hacked_twin.op"? why not take a change on _unsafe_index_put? looking for your reply. Thanks a lot!
> > 
> > 
> > The error you got is because torch-mlir does not contain lowering for `torch.aten._unsafe_index_put` op.
> 
> Thanks for your quick reply, could you give some advice to process the issue?

The issue can be resolved by adding the missing op' lowering in Torch-MLIR.

**Comment by bailuan** [comment]
> > > > Hi, @vivekkhandelwal1. I encountered the same issue when I tried to convert llama2 model: `iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline: error: unknown: failed to legalize operation 'torch.operator' that was explicitly marked illegal note: unknown: see current operation: %1251 = "torch.operator"(%1249, %1250, %1247, %13) <{name = "torch.aten._unsafe_index_put"}> : (!torch.vtensor<[32000,288],f32>, !torch.list<optional<vtensor>>, !torch.vtensor<[1,256,288],f32>, !torch.bool) -> !torch.vtensor<[32000,288],f32>` could you tell me the version of your torch? I saw the method within "unsafe_index_put" in my torch 2.1.0 is : `namespace at { namespace native { TORCH_API at::Tensor _unsafe_index_put(const at::Tensor & self, const c10::List<c10::optional<at::Tensor>> & indices, const at::Tensor & values, bool accumulate=false); } // namespace native } // namespace at` where is the ".hacked_twin.op"? why not take a change on _unsafe_index_put? looking for your reply. Thanks a lot!
> > > 
> > > 
> > > The error you got is because torch-mlir does not contain lowering for `torch.aten._unsafe_index_put` op.
> > 
> > 
> > Thanks for your quick reply, could you give some advice to process the issue?
> 
> The issue can be resolved by adding the missing op' lowering in Torch-MLIR.

Thank you! I will learn how to do that!

**Comment by vivekkhandelwal1** [comment]
> > > > > Hi, @vivekkhandelwal1. I encountered the same issue when I tried to convert llama2 model: `iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline: error: unknown: failed to legalize operation 'torch.operator' that was explicitly marked illegal note: unknown: see current operation: %1251 = "torch.operator"(%1249, %1250, %1247, %13) <{name = "torch.aten._unsafe_index_put"}> : (!torch.vtensor<[32000,288],f32>, !torch.list<optional<vtensor>>, !torch.vtensor<[1,256,288],f32>, !torch.bool) -> !torch.vtensor<[32000,288],f32>` could you tell me the version of your torch? I saw the method within "unsafe_index_put" in my torch 2.1.0 is : `namespace at { namespace native { TORCH_API at::Tensor _unsafe_index_put(const at::Tensor & self, const c10::List<c10::optional<at::Tensor>> & indices, const at::Tensor & values, bool accumulate=false); } // namespace native } // namespace at` where is the ".hacked_twin.op"? why not take a change on _unsafe_index_put? looking for your reply. Thanks a lot!
> > > > 
> > > > 
> > > > The error you got is because torch-mlir does not contain lowering for `torch.aten._unsafe_index_put` op.
> > > 
> > > 
> > > Thanks for your quick reply, could you give some advice to process the issue?
> > 
> > 
> > The issue can be resolved by adding the missing op' lowering in Torch-MLIR.
> 
> Thank you! I will learn how to do that!

You can follow this PR to add the support for the `unsafe_index_put` op.

**Pull request merged**
