### PR TITLE
MaxPool1d lowering to linalg

### PR DESCRIPTION
**Pull request by NeverRaR**

### CODE REVIEW

**Comment by NeverRaR** [comment]
@vivekkhandelwal1 This PR requires a review.

**Review by vivekkhandelwal1 — APPROVED** [review]
LGTM

**Comment by NeverRaR** [comment]
@vivekkhandelwal1 CI requires approval.

**Comment by NeverRaR** [comment]
@vivekkhandelwal1 remove duplicated torch shape function to fix unit test error

**Comment by NeverRaR** [comment]
@vivekkhandelwal1  CI failed because of unexpectedly passed tests in e2e test which makes me confused.
```
  ****** Unexpectedly Passed tests - 3 tests
      XPASS - "MaxPool1dEmptyStrideStaticModule_basic"
      XPASS - "MaxPool1dStaticCeilModeTrueModule_basic"
      XPASS - "MaxPool1dStaticModule_basic"
```
Why are these tests unexpectedly passed tests? How to fix it?

**Comment by penguin-wwy** [comment]
> @vivekkhandelwal1 CI failed because of unexpectedly passed tests in e2e test which makes me confused.
> 
> ```
>   ****** Unexpectedly Passed tests - 3 tests
>       XPASS - "MaxPool1dEmptyStrideStaticModule_basic"
>       XPASS - "MaxPool1dStaticCeilModeTrueModule_basic"
>       XPASS - "MaxPool1dStaticModule_basic"
> ```
> 
> Why are these tests unexpectedly passed tests? How to fix it? I'm sorry to keep asking questions , I haven't reproduced the problem locally.

Add these test cases to the TOSA_PASS_SET or MAKE_FX_TOSA_PASS_SET in projects/pt1/e2e_testing/xfail_sets.py.

**Comment by penguin-wwy** [comment]
> > > @vivekkhandelwal1 CI failed because of unexpectedly passed tests in e2e test which makes me confused.
> > > ```
> > >   ****** Unexpectedly Passed tests - 3 tests
> > >       XPASS - "MaxPool1dEmptyStrideStaticModule_basic"
> > >       XPASS - "MaxPool1dStaticCeilModeTrueModule_basic"
> > >       XPASS - "MaxPool1dStaticModule_basic"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Why are these tests unexpectedly passed tests? How to fix it? I'm sorry to keep asking questions , I haven't reproduced the problem locally.
> > 
> > 
> > Add these test cases to the TOSA_PASS_SET or MAKE_FX_TOSA_PASS_SET in projects/pt1/e2e_testing/xfail_sets.py.
> 
> Does this mean that I still need to implement MaxPool1d in Conversion/TorchToTosa?

If you prefer, you can do that. Alternatively, you can just modify within MAKE_FX_TOSA_PASS_SET, as tosa and make_fx_tosa are two different test config.

**Comment by NeverRaR** [comment]
> > > > @vivekkhandelwal1 CI failed because of unexpectedly passed tests in e2e test which makes me confused.
> > > > ```
> > > >   ****** Unexpectedly Passed tests - 3 tests
> > > >       XPASS - "MaxPool1dEmptyStrideStaticModule_basic"
> > > >       XPASS - "MaxPool1dStaticCeilModeTrueModule_basic"
> > > >       XPASS - "MaxPool1dStaticModule_basic"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Why are these tests unexpectedly passed tests? How to fix it? I'm sorry to keep asking questions , I haven't reproduced the problem locally.
> > > 
> > > 
> > > Add these test cases to the TOSA_PASS_SET or MAKE_FX_TOSA_PASS_SET in projects/pt1/e2e_testing/xfail_sets.py.
> > 
> > 
> > Does this mean that I still need to implement MaxPool1d in Conversion/TorchToTosa?
> 
> If you prefer, you can do that. Alternatively, you can just modify within MAKE_FX_TOSA_PASS_SET, as tosa and make_fx_tosa are two different test config.

I get it, thanks a lot!

**Comment by NeverRaR** [comment]
@vivekkhandelwal1 I think this PR is ready to merge

**Comment by vivekkhandelwal1** [comment]
> @vivekkhandelwal1 I think this PR is ready to merge

Merged

**Pull request merged**
