### PR TITLE
* [tosa] Support for Rsqrt legalization

### PR DESCRIPTION
**Pull request by anupgangwar**
Signed-off-by: Anup Gangwar <anup.gangwar@arm.com>

### CODE REVIEW

**Comment by sjarus** [comment]
@silvasean , we have the first contribution from our colleague Anup here.

**Comment by silvasean** [comment]
Welcome Anup! This looks great!! Can you rebase your patch so the CI passes?

**Comment by silvasean** [comment]
@sjarus btw, is there a plan to add pretty syntax for the TOSA dialect? That would help make the IR more readable, and also generally make the TOSA dialect seem "more real" (for better or worse, people do key off the level of attention to detail / love+care that a dialect has received).

**Comment by sjarus** [comment]
> @sjarus btw, is there a plan to add pretty syntax for the TOSA dialect? That would help make the IR more readable, and also generally make the TOSA dialect seem "more real" (for better or worse, people do key off the level of attention to detail / love+care that a dialect has received).

Ah didn't realize it looked that ugly :-) this is one of those things where we just weren't well accustomed with the MLIR rubric or ideal. We'd be happy to clean up the parser/printers to make the dialect form more easier to read - could you point us to resources that would help us integrate this ?

**Comment by silvasean** [comment]
This is the doc page for the `let assemblyFormat`: https://mlir.llvm.org/docs/OpDefinitions/#declarative-assembly-format

You can see examples in the `torch` dialect for what the common idioms are: https://github.com/llvm/torch-mlir/blob/6dabf185f5c819fddcfa167c82833e83fa9b90a1/include/torch-mlir/Dialect/Torch/IR/GeneratedAtenOps.td#L102

We actually generate the assemblyFormat's for the generic ops in a simple closed form in the torch ods generator script: https://github.com/llvm/torch-mlir/blob/6dabf185f5c819fddcfa167c82833e83fa9b90a1/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py#L329

for ops with control flow, it's a bit trickier. Here are some examples:
torch.prim.If: https://github.com/llvm/torch-mlir/blob/6dabf185f5c819fddcfa167c82833e83fa9b90a1/include/torch-mlir/Dialect/Torch/IR/TorchOps.td#L485 + https://github.com/llvm/torch-mlir/blob/6dabf185f5c819fddcfa167c82833e83fa9b90a1/lib/Dialect/Torch/IR/TorchOps.cpp#L287
torch.prim.Loop: https://github.com/llvm/torch-mlir/blob/6dabf185f5c819fddcfa167c82833e83fa9b90a1/include/torch-mlir/Dialect/Torch/IR/TorchOps.td#L438 + https://github.com/llvm/torch-mlir/blob/6dabf185f5c819fddcfa167c82833e83fa9b90a1/lib/Dialect/Torch/IR/TorchOps.cpp#L253

**Review by sjarus — APPROVED** [review]
@silvasean I redid the checks by starting the build again. The earlier failure appears to have been a transient one, and this looks good to go. 

Have you seen such a transient build failure before ? I verified off Anup's local repo that he's at the head.

**Comment by silvasean** [comment]
> @silvasean I redid the checks by starting the build again. The earlier failure appears to have been a transient one, and this looks good to go.
> 
> Have you seen such a transient build failure before ? I verified off Anup's local repo that he's at the head.

I thought it was just a failure that got fixed forward, but I can't seem to find the fix-forward... maybe it is a nondeterministic test :( . I'll keep an eye out.

**Pull request merged**
