### PR TITLE
[torch-mlir] add MPACT as an example torch-mlir based compiler

### PR DESCRIPTION
**Pull request by aartbik**
Rationale:
In addition to IREE and Blade, MPACT provides an MLIR-based example of a PyTorch compiler that uses TORCH-MLIR. It also illustrates propagating sparsity from sparse PyTorch into MLIR, a feature that is not widespread in DL compilers yet.

### CODE REVIEW

**Review by reidtatge — APPROVED** [review]

**Review by stellaraccident — COMMENTED** [review]
Is this project still active? The last substantive commit I see is from seven months ago. It is of a substantially different level of maturity and investment than the other two and I'd prefer that we only list projects that are active.

**Comment by aartbik** [comment]
> Is this project still active? The last substantive commit I see is from seven months ago. It is of a substantially different level of maturity and investment than the other two and I'd prefer that we only list projects that are active.

I plan to actively work on this again. But regardless, I thought it would be nice illustration of a (perhaps still academic) way to propagate sparsity into an MLIR pipeline.

**Comment by stellaraccident** [comment]
There isn't much there. Can we only use this page for advertising projects that are active and somewhat mature.

In the new year, we can refactor the docs to have sections for things that are more niche or up and coming.

**Comment by aartbik** [comment]
> There isn't much there. Can we only use this page for advertising projects that are active and somewhat mature.
> 
> In the new year, we can refactor the docs to have sections for things that are more niche or up and coming.

Noted. I will remove.

**Pull request merged**
