### PR TITLE
build: manually update PyTorch version

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
Set PyTorch and TorchVision version to nightly release 2024-02-07.

Signed-Off By: Vivek Khandelwal <vivekkhandelwal1424@gmail.com>

### CODE REVIEW

**Review by Abhishek-Varma — APPROVED** [review]

**Comment by stellaraccident** [comment]
Looks like a non determinism and an overly restrictive check test. Will need to share at it a bit.

**Review by stellaraccident — CHANGES_REQUESTED** [review]
On closer look, the test looks correct and there is some drift on the PyTorch side causing additional arguments to be captured. They note that these APIs are in flux, so we'll need to figure out how to adapt to both.

**Comment by sjain-stanford** [comment]
Upon some digging, here's the imported IR with the new `torch-nightly`: 
```
module {                                                                                                                                                                                          
  func.func @main(%arg0: !torch.vtensor<[1,4],f32>, %arg1: !torch.vtensor<[3,1],f32>, %arg2: !torch.vtensor<[3,4],f32>) -> !torch.vtensor<[3,4],f32> {                                            
    %0 = torch.aten.tanh %arg2 : !torch.vtensor<[3,4],f32> -> !torch.vtensor<[3,4],f32>                                                                                                           
    %1 = torch.aten.mul.Tensor %0, %arg0 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[1,4],f32> -> !torch.vtensor<[3,4],f32>                                                                      
    %2 = torch.aten.mul.Tensor %1, %arg1 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[3,1],f32> -> !torch.vtensor<[3,4],f32>                                                                      
    %3 = torch.vtensor.literal(dense<0.113757931> : tensor<1x1xf32>) : !torch.vtensor<[1,1],f32>                                                                                                  
    %4 = torch.aten.mul.Tensor %2, %3 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[1,1],f32> -> !torch.vtensor<[3,4],f32>                                                                         
    return %4 : !torch.vtensor<[3,4],f32>                                                                                                                                                         
  }                                                                                                                                                                                               
}               
```
The key difference is what used to be `dialect_resources` are now arguments to the main module (specifically the tensors of shape [1, 4] and [3, 1]). @vivekkhandelwal1 your changes do make the test pass locally (with `torch-nightly`), however the CI failure is surfaced with `torch-stable` (which then preempts the `torch-nightly` run) and this makes sense knowing that we pull in 2.2.0-stable (2.3.0-stable isn't released yet). @stellaraccident not sure how you'd want to proceed but listing here a few options that come to mind: 
1. make torch-stable CI optional until 2.3 is released
2. maintain two separate sets of tests and any conversions / dialect passes (for nightly vs stable) - this might be an overkill though

**Comment by stellaraccident** [comment]
https://github.com/llvm/torch-mlir/blob/9b967f6b5ab49b344af9a2c56659784502f2c488/python/torch_mlir/extras/fx_importer.py#L396

**Comment by sjain-stanford** [comment]
Is it likely that we're failing to lift buffers here, due to some change on the FX IR side of things? 
```python
        # Lift buffers.
        for input_name, state_name in sig.inputs_to_buffers.items():
            try:
                state_value = state_dict[state_name]
            except KeyError as e:
                raise AssertionError("Could not find state mapping for buffer") from e
            arg_replacements[input_name] = state_value
```

**Comment by stellaraccident** [comment]
> I'm still new to the fx_importer internals, so I appreciate those pointers. Let me try to share my observations so far:
> 
> > What are dialect resources?
> 
> From the mlir [docstrings](https://github.com/llvm/llvm-project/blob/2fcfc9754a16805b81e541dc8222a8b5cf17a121/mlir/include/mlir/IR/AsmState.h#L35-L80):
> 
> > Resources are a mechanism by which dialects, and external clients, may attach additional information when parsing or printing IR without that information being encoded in the IR itself. Resources are not uniqued within the MLIR context, are not attached directly to any operation, and are solely intended to live and be processed outside of the immediate IR.
> 
> To be clear though, I think dialect_resources is just a representational detail, what I meant was whether buffers/parameters are captured as `torch.vtensor.literal` (frozen, not main inputs) or `torch.vtensor` (main inputs).
> 
> For context, this is the imported IR with `torch==2.3.0.dev20240122`. It looks like in this version, both buffers (free tensors) and parameters in the original pytorch were captured as `torch.vtensor.literal` in the `Torch` dialect.
> 
> ```
> module {                                                                                                                                                                                          
>   func.func @main(%arg0: !torch.vtensor<[3,4],f32>) -> !torch.vtensor<[3,4],f32> {                                                                                                                
>     %0 = torch.aten.tanh %arg0 : !torch.vtensor<[3,4],f32> -> !torch.vtensor<[3,4],f32>                                                                                                           
>     %1 = torch.vtensor.literal(dense_resource<torch_tensor_1_4_torch.float32> : tensor<1x4xf32>) : !torch.vtensor<[1,4],f32>                                                                      
>     %2 = torch.aten.mul.Tensor %0, %1 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[1,4],f32> -> !torch.vtensor<[3,4],f32>                                                                         
>     %3 = torch.vtensor.literal(dense_resource<torch_tensor_3_1_torch.float32> : tensor<3x1xf32>) : !torch.vtensor<[3,1],f32>                                                                      
>     %4 = torch.aten.mul.Tensor %2, %3 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[3,1],f32> -> !torch.vtensor<[3,4],f32>                                                                         
>     %5 = torch.vtensor.literal(dense<0.28747952> : tensor<1x1xf32>) : !torch.vtensor<[1,1],f32>                                                                                                   
>     %6 = torch.aten.mul.Tensor %4, %5 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[1,1],f32> -> !torch.vtensor<[3,4],f32>                                                                         
>     return %6 : !torch.vtensor<[3,4],f32>                                                                                                                                                         
>   }                                                                                                                                                                                               
> }                                                                                                                                                                                                 
>                                                                                                                                                                                                   
> {-#                                                                                                                                                                                               
>   dialect_resources: {                                                                                                                                                                            
>     builtin: {                                                                                                                                                                                    
>       torch_tensor_1_4_torch.float32: "0x04000000F6A4D43E49A5953F12DB9C3FF4AF22BE",                                                                                                               
>       torch_tensor_3_1_torch.float32: "0x040000007AD7D5BFFA0C32BE9240B33F"                                                                                                                        
>     }                                                                                                                                                                                             
>   }                                                                                                                                                                                               
> #-}          
> ```
> 
> And as of `torch==2.3.0.dev20240207`, the imported IR uses `torch.vtensor.literal` only for parameters, whereas buffers are main `torch.vtensor` inputs.
> 
> ```
> module {                                                                                                                                                                                          
>   func.func @main(%arg0: !torch.vtensor<[1,4],f32>, %arg1: !torch.vtensor<[3,1],f32>, %arg2: !torch.vtensor<[3,4],f32>) -> !torch.vtensor<[3,4],f32> {                                            
>     %0 = torch.aten.tanh %arg2 : !torch.vtensor<[3,4],f32> -> !torch.vtensor<[3,4],f32>                                                                                                           
>     %1 = torch.aten.mul.Tensor %0, %arg0 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[1,4],f32> -> !torch.vtensor<[3,4],f32>                                                                      
>     %2 = torch.aten.mul.Tensor %1, %arg1 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[3,1],f32> -> !torch.vtensor<[3,4],f32>                                                                      
>     %3 = torch.vtensor.literal(dense<0.113757931> : tensor<1x1xf32>) : !torch.vtensor<[1,1],f32>                                                                                                  
>     %4 = torch.aten.mul.Tensor %2, %3 : !torch.vtensor<[3,4],f32>, !torch.vtensor<[1,1],f32> -> !torch.vtensor<[3,4],f32>                                                                         
>     return %4 : !torch.vtensor<[3,4],f32>                                                                                                                                                         
>   }                                                                                                                                                                                               
> }     
> ```
> 
> I can confirm that the `prog.graph` is the same at the location you linked above, but after the "remove lifted placeholders" bit, they do differ. I've pasted the `prog.graph` right before we `self.import_stateless_graph(g)`:
> 
> #### torch==2.3.0.dev20240122
> ```
> graph():                                                                                                                                                                                          
>     %l_x_ : [num_users=1] = placeholder[target=l_x_]                                                                                                                                              
>     %tanh : [num_users=1] = call_function[target=torch.ops.aten.tanh.default](args = (%l_x_,), kwargs = {})                                                                                       
>     %mul : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%tanh, tensor([[ 0.5324,  2.2165, -1.7662, -0.4014]])), kwargs = {})                                           
>     %mul_1 : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%mul, tensor([[-0.5790],                                                                                     
>         [-1.1343],                                                                                                                                                                                
>         [ 1.1203]])), kwargs = {})                                                                                                                                                                
>     %mul_2 : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%mul_1, Parameter containing:                                                                                
> tensor([[1.0322]], requires_grad=True)), kwargs = {})                                                                                                                                             
>     return (mul_2,)     
> ```
> 
> #### torch==2.3.0.dev20240207
> ```
> graph():                                                                                                                                                                                          
>     %arg1_1 : [num_users=1] = placeholder[target=arg1_1]                                                                                                                                          
>     %arg2_1 : [num_users=1] = placeholder[target=arg2_1]                                                                                                                                          
>     %l_x_ : [num_users=1] = placeholder[target=l_x_]                                                                                                                                              
>     %tanh : [num_users=1] = call_function[target=torch.ops.aten.tanh.default](args = (%l_x_,), kwargs = {})                                                                                       
>     %mul : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%tanh, %arg1_1), kwargs = {})                                                                                  
>     %mul_1 : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%mul, %arg2_1), kwargs = {})                                                                                 
>     %mul_2 : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%mul_1, Parameter containing:                                                                                
> tensor([[0.5684]], requires_grad=True)), kwargs = {})                                                                                                                                             
>     return (mul_2,)           
> ```

Ok, I didn't know if we were talking about some torch thing.

So this is just some drift in terms of how PyTorch is representing captured module parameters. The specific way we are using the ExportedProgram (linked prior) is "lifting" those to globals to match the behavior that torch-mlir has traditionally had (i.e. the test is correct). I just open coded that in the fx_importer as part of upstreaming, and the PyTorch docs very explicitly say that the ExportedProgram API can/will change. So I think some semantic changed and we need to adapt to it. Maybe they are just calling it something else... in any case, I worked out the current incantation and someone will need to figure out what changed.

In our downstream, we aren't using ExportedProgram yet (using a lower level facility), so that is just a torch-mlir thing to try to have something standalone, but we'll need to adapt as the PT team settles on the final semantics.

**Comment by stellaraccident** [comment]
This was my relevant archaology:

```
        The ExportedProgram form differs from some of the earlier work primarily in
        how it deals with references to external tensors from "outside". In this form,
        all such references are checked to have originated from within the exported
        scope or from an @assume_constant_result wrapped function. Then they are
        transformed to graph inputs and stashed in one of two data structures on
        the ExportedProgram:
        inputs_to_buffers / buffers : For non-parameter buffers.
        inputs_to_parameters / parameters : For parameter buffers.
        The values of the mapping in inputs_to_{buffers|parameters} are in the
        state_dict. This replaces get_attr nodes that would have classically been
        present during lower level tracing.
```

Basically, what the ExportedProgram is doing is making everything an argument but keeping some accounting details off to the side. Then we need to read that side data and make the transformation to the form we want.

**Comment by stellaraccident** [comment]
(I should also mention that there may be bugs in PyTorch -- it is possible that this nightly just regressed. This stuff is under active development)

**Comment by sjain-stanford** [comment]
I had the same interpretation from reading your docstrings that the original test (ie. before the modifications in this PR)  looks correct, and the tensor placeholders not being lifted might be an issue that the failing test is correctly flagging (this probably needs some massaging in the fx_importer to adapt to the newer torch conventions). Thanks for sharing the historical context.

**Comment by sjain-stanford** [comment]
One bit that might be relevant here is that I don't see those buffers in the `prog.state_dict` at all. 

```
(Pdb) print(prog.state_dict)                                                                                                                                                                      
OrderedDict([('p', Parameter containing:                                                                                                                                                          
tensor([[0.5684]], requires_grad=True))])   
```

And `sig.inputs_to_buffers` is empty. 

This is the relevant bit in `torch/export`: https://sourcegraph.com/github.com/pytorch/pytorch@24bdd03d23d883e3eaa19b3002e62995987dfd0f/-/blob/torch/export/graph_signature.py?L359

Had a change from 11 days ago: https://github.com/pytorch/pytorch/pull/118969

**Comment by stellaraccident** [comment]
I expect that is the failing patch. Our test case of this is fairly trivial and could be expressed on that PR in a way they would understand. We could just ask for a recommendation for how to get the semantics we want.

**Comment by stellaraccident** [comment]
The heuristic we were using might be not great. Note the changes to the ONNX importer:

```
                    InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg0_1'), target='conv1.weight'),
                    InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg1_1'), target='conv2.weight'),
                    InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg2_1'), target='fc1.weight'),
                    InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg3_1'), target='fc2.weight'),
                    InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='arg4_1'), target='my_buffer2'),
                    InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='arg5_1'), target='my_buffer1'),
                    InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='l_x_'), target=None),
                    InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg1'), target=None)
                    InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg0_1'),
                              target='conv1.weight', persistent=None),
                    InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg1_1'),
                              target='conv2.weight', persistent=None),
                    InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg2_1'),
                              target='fc1.weight', persistent=None),
                    InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg3_1'),
                              target='fc2.weight', persistent=None),
                    InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='arg4_1'),
                              target='my_buffer2', persistent=True),
                    InputSpec(kind=<InputKind.BUFFER: 3>, arg=TensorArgument(name='arg5_1'),
                              target='my_buffer1', persistent=True),
                    InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='l_x_'),
                              target=None, persistent=None),
                    InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg1'),
                              target=None, persistent=None)
```

We can probably do our lifting based on the argument kind. Also, I expect these things may be landing in the `constants` vs `state_dict` after this patch.

**Comment by sjain-stanford** [comment]
> Also, I expect these things may be landing in the constants vs state_dict after this patch.

That's true.
```
(Pdb) print(prog.constants)                                                                                                                                                                       
{'get_a': tensor([[-0.5663,  0.3731, -0.8920, -1.5091]]), 
 'L__self___b': tensor([[ 1.5410],                                                                                                       
                        [ -0.2934],                                                                                                                                                                                
                        [ -2.1788]])}
```

**Comment by stellaraccident** [comment]
That would be easy to conditional code so it works on both versions.

**Comment by sjain-stanford** [comment]
@stellaraccident do you see any issues with this patch?
```patch
diff --git a/python/torch_mlir/extras/fx_importer.py b/python/torch_mlir/extras/fx_importer.py                                                                                                    
index 5328e873..7d24ca0b 100644                                                                                                                                                                   
--- a/python/torch_mlir/extras/fx_importer.py                                                                                                                                                     
+++ b/python/torch_mlir/extras/fx_importer.py                                                                                                                                                     
@@ -341,6 +341,7 @@ class FxImporter:                                                                                                                                                             
         """                                                                                                                                                                                      
         sig = prog.graph_signature                                                                                                                                                               
         state_dict = prog.state_dict                                                                                                                                                             
+        constants = prog.constants                                                                                                                                                               
         arg_replacements: dict[str, Any] = {}                                                                                                                                                    
         # Lift buffers.                                                                                                                                                                          
         for input_name, state_name in sig.inputs_to_buffers.items():                                                                                                                             
@@ -349,6 +350,13 @@ class FxImporter:                                                                                                                                                            
             except KeyError as e:                                                                                                                                                                
                 raise AssertionError("Could not find state mapping for buffer") from e                                                                                                           
             arg_replacements[input_name] = state_value                                                                                                                                           
+        # Lift tensor constants.                                                                                                                                                                 
+        for input_name, state_name in sig.inputs_to_lifted_tensor_constants.items():                                                                                                             
+            try:                                                                                                                                                                                 
+                state_value = constants[state_name]                                                                                                                                              
+            except KeyError as e:                                                                                                                                                                
+                raise AssertionError("Could not find state mapping for buffer") from e                                                                                                           
+            arg_replacements[input_name] = state_value                                                                                                                                           
```

**Comment by sjain-stanford** [comment]
Actually the above patch should work for both versions (it collects both persistent buffers and non-persistent buffers).

**Comment by stellaraccident** [comment]
> Actually the above patch should work for both versions (it collects both persistent buffers and non-persistent buffers).

I think that should be fine for the narrow case this function was defined for (i.e. "freeze everything")... which is why I defined it that way. Eventually folks will want something more and that can have different rules.

**Comment by stellaraccident** [comment]
Not sure if you can take over Vivek's branch, but if you can feel free to push there and we can land. Otherwise, can do a new PR.

**Comment by sjain-stanford** [comment]
I can't push to Vivek's fork, but here's the PR that adds on top of Vivek's commit: https://github.com/llvm/torch-mlir/pull/2902

**Comment by stellaraccident** [comment]
Fixed by #2902

**Pull request closed without merging**
