### PR TITLE
[Resubmit] Add e2e support for aten logical or/and/xor/not ops

### PR DESCRIPTION
**Pull request by li-plus**
This PR fixed the e2e testing failure mentioned in issue #1758 regarding to PR #1752.

The e2e test added in #1752 triggered the error because the model was compiled with `dtype=float64` but fed with a random tensor with `dtype=float32`. It might cause precision error if the random values are close to zero when converting to boolean.

In this PR the model is compiled with `dtype=float32` to be consistent with input data. The random float tensor shape also expanded from `[5]` to `[256]` to minimize non-determinacy. If this CI has passed, it is unlikely that the future CI will fail.

@ashay @ramiro050 Would you review this PR?

### CODE REVIEW

**Comment by li-plus** [comment]
@ramiro050 I also added a static-shape e2e test for each new op that will pass in MHLO backend.

**Review by ashay — APPROVED** [review]
Thanks for resolving the problem quickly!  LGTM, but let's wait for Ramiro's review before merging this.

**Review by ramiro050 — APPROVED** [review]
Good catch on the `float64` issue, and thanks for adding the tests that check the MHLO lowering!

**Comment by li-plus** [comment]
Would you mind merging this PR for me? I still don't have write access of this repo.

**Pull request merged**
