### PR TITLE
torch: [nfc] use `WalkResult::isInterrupted()` instead of booleans

### PR DESCRIPTION
**Pull request by ashay**
An upstream MLIR bug (that was recently fixed) caused the result to be
ignored for Region- and Block-visitor functions.  Now that the bug is
fixed, we don't need an auxiliary boolean to track whether the visitor
function has succeeded.

### CODE REVIEW

**Review by silvasean — APPROVED** [review]
Thanks!

**Comment by silvasean** [comment]
btw, are you on discord @ashay?

**Comment by ashay** [comment]
> btw, are you on discord?

Yeah, I am @radiosonde on Discord/LLVM.

**Comment by silvasean** [comment]
@ashay can you add me as a friend on Discord/LLVM? Your account doesn't seem to be accepting DM's/friend requests.

**Comment by ashay** [comment]
Hey @silvasean, just saw your message.  Sorry about the delay.  Added now.

**Pull request merged**
