### PR TITLE
[TorchToLinalg] Use `linalg.transpose` instead of `generic` in `permuteTensor`

### PR DESCRIPTION
**Pull request by CoTinker**
This PR changes the lowering to use `linalg.transpose` instead of `linalg.generic` in `torch_to_linalg::permuteTensor`.

### CODE REVIEW

**Review by ubfx — COMMENTED** [review]
I think this makes sense, but there seems to be a problem with 0D-tensors in the e2e tests?

**Comment by CoTinker** [comment]
I'll take a look at it.

**Comment by CoTinker** [comment]
I wonder if we should add a folder for `aten.permute` with 0-D input.

**Comment by vivekkhandelwal1** [comment]
> I wonder if we should add a folder for `aten.permute` with 0-D input.

Yeah, that's a nice thing to do. You may do it in the same PR or in another one as you wish.

**Review by vivekkhandelwal1 — APPROVED** [review]
LGTM

**Comment by CoTinker** [comment]
Thanks, I think it's better to open another PR for the folder.

**Pull request merged**
