### PR TITLE
Adding stablehlo dialects support for torch-mlir-opt tool

### PR DESCRIPTION
**Pull request by chenkanhw**
I tried to use following commad to debug my program:

> ./torch-mlir/build/bin/torch-mlir-opt --chlo-legalize-to-hlo ./xxx-chlo.mlir

It showed torch-mlir-opt tool didn't support chlo dialect:

`error: Dialect 'chlo' not found for custom op 'chlo.broadcast_add'`

This PR tries to add stablehlo dialects support for this tool.

### CODE REVIEW

**Review by silvasean — APPROVED** [review]

**Comment by chenkanhw** [comment]
@silvasean thanks for your review. I saw the TORCH_MLIR_ENABLE_STABLEHLO was disabled on macOS in buildAndTest.yml file. It caused a build failure on that platform for this PR. I don't know the reason why keeping this configuration. Can I turn it on?

**Comment by silvasean** [comment]
You will need to ifdef it like here: https://github.com/llvm/torch-mlir/blob/268364e0615c18363f31da5441a06490bc35d720/lib/Dialect/TorchConversion/Transforms/Passes.cpp#L124

**Comment by chenkanhw** [comment]
@silvasean modified. Thanks.

**Comment by ashay** [comment]
Merging since the PR is approved, all tests pass, and because there is no merge conflicts.

**Pull request merged**
