### PR TITLE
Revert to green

### PR DESCRIPTION
**Pull request by silvasean**
Revert some patches to get the build green again.

Fixes https://github.com/llvm/torch-mlir/issues/807

### CODE REVIEW

**Comment by silvasean** [comment]
@vivekkhandelwal1 , I appreciate the factoring into smaller commits, but in this case, because they were each very dependent on the previous ones, I had to revert multiple to get the build green again.

**Comment by pashu123** [comment]
Hi, @silvasean I tried running this https://github.com/llvm/torch-mlir/blob/main/build_tools/torchscript_e2e_heavydep_tests/generate_serialized_tests.sh script. Shouldn't we make sure that this script runs to generate serialized scripts?

**Comment by silvasean** [comment]
> Hi, @silvasean I tried running this https://github.com/llvm/torch-mlir/blob/main/build_tools/torchscript_e2e_heavydep_tests/generate_serialized_tests.sh script. Shouldn't we make sure that this script runs to at least generate serialized scripts?

Yes, that would be great. Can you add that?

**Comment by vivekkhandelwal1** [comment]
> Hi, @silvasean I tried running this https://github.com/llvm/torch-mlir/blob/main/build_tools/torchscript_e2e_heavydep_tests/generate_serialized_tests.sh script. Shouldn't we make sure that this script runs to at least generate serialized scripts?

It's failing for two tests: hf_big_bird and timm_resnest. I will remove those tests till they are fixed.

**Comment by vivekkhandelwal1** [comment]
@silvasean, I have to again add these commits once the issue with them is fixed, right?

**Comment by vivekkhandelwal1** [comment]
Hi @silvasean, I have found a fix to this issue. The error was with the test case. Should I create a new PR with all commits squashed or keep them separate?

**Comment by silvasean** [comment]
It's up to you. I would personally squash them due to the mechanical nature, and the fact that they don't apply independently.

**Pull request merged**
