### PR TITLE
Revert "Revert updating mlir_native_functions.cpp signature"

### PR DESCRIPTION
**Pull request by henrytwo**
Reverts llvm/torch-mlir#1281 and unblocks CI failure from updated LTC API + tests

It looks like the revert of the PyTorch PR got reverted... https://github.com/pytorch/pytorch/commit/9790d90e4b0288796ab44a6b4979db0a67580ba8

### CODE REVIEW

**Comment by henrytwo** [comment]
Closing, since https://github.com/llvm/torch-mlir/pull/1289 includes these changes

**Comment by powderluv** [comment]
looks like we need to revert the revert of the revert again ?

**Comment by powderluv** [comment]
https://github.com/llvm/torch-mlir/runs/8049903605?check_suite_focus=true

**Comment by henrytwo** [comment]
@antoniojkim Could you look into this? This change was added back in your PR https://github.com/llvm/torch-mlir/pull/1289

**Comment by powderluv** [comment]
https://github.com/pytorch/pytorch/commit/c7edcd69683f6e3b08305ed0d4621e148fbfbe17

**Comment by henrytwo** [comment]
Maybe if we wait long enough, this reversion will also get reverted 😝

**Pull request closed without merging**
