### PR TITLE
[CI] Enable the tests for fx_importer in the CI

### PR DESCRIPTION
**Pull request by penguin-wwy**
Replace the torchdynamo e2e with the fx_importer e2e

### CODE REVIEW

**Comment by stellaraccident** [comment]
Thanks - was just trying to put such a patch together based on your mesage on #3163. Let's see what this one does.

**Comment by stellaraccident** [comment]
Looks like just a handful of tests we should xfail, then can land this.

**Comment by penguin-wwy** [comment]
done

**Review by stellaraccident — APPROVED** [review]

**Comment by stellaraccident** [comment]
Awesome. If you wouldn't mind rebasing your fx_importer PRs and getting the CI to run them?

**Pull request merged**
