### PR TITLE
[MLIR][TORCH] Add OnnxToTorch lowering for Einsum op

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
Signed-Off By: Vivek Khandelwal <vivekkhandelwal1424@gmail.com>

### CODE REVIEW

**Review by zjgarvey — APPROVED** [review]
LGTM

**Comment by zjgarvey** [comment]
Do you know what might be failing on the stable tests? The details aren't really showing up for me.

**Comment by vivekkhandelwal1** [comment]
> Do you know what might be failing on the stable tests? The details aren't really showing up for me.

Yeah, I'm also trying to find that but not seeing any error message.

**Comment by zjgarvey** [comment]
> > Do you know what might be failing on the stable tests? The details aren't really showing up for me.
> 
> Yeah, I'm also trying to find that but not seeing any error message.

I'm guessing something is crashing the tests. I'll try checking it out locally if you want.

**Comment by vivekkhandelwal1** [comment]
> > > Do you know what might be failing on the stable tests? The details aren't really showing up for me.
> > 
> > 
> > Yeah, I'm also trying to find that but not seeing any error message.
> 
> I'm guessing something is crashing the tests. I'll try checking it out locally if you want.

No worries, I can take a look at it tomorrow.

**Review by rsuderman — APPROVED** [review]

**Pull request merged**
