### PR TITLE
[onnx] Support of onnx.Greater, onnx.Less, onnx.GreaterOrEqual to Torch

### PR DESCRIPTION
**Pull request by afalkenberg1**
The three remaining compare operations
onnx.Greater 
onnx.Less 
onnx.GreaterOrEqual

Are also added with this push request. 
This concludes a set of basic tensor compare functions.

### CODE REVIEW

**Comment by afalkenberg1** [comment]
Hello checking in the rest of the compare functions. 
Thanks for you help @qedawkins

**Comment by afalkenberg1** [comment]
Hi all, please review 
@stellaraccident @vivekkhandelwal1 
@qedawkins
Thank you for you help

**Review by stellaraccident — APPROVED** [review]
lgtm. needs conflicts resolved to land.

**Comment by afalkenberg1** [comment]
Hello ready to merge 
@stellaraccident @vivekkhandelwal1
@qedawkins
Thanks

**Pull request merged**
