### PR TITLE
[TOSA] Add aten.masked_fill.Tensor/Scalar support

### PR DESCRIPTION
**Pull request by AmosLewis**
This issue is found when converting deberta model https://github.com/nod-ai/SHARK/issues/493.

### CODE REVIEW

**Comment by AmosLewis** [comment]
Any idea to this kind of bug? Where is the golden value?
```
➜  torch-mlir git:(masked_fill_tosa) ✗ python -m e2e_testing.main -c tosa -f "MaskedFillTensorIntValueStaticModule_basic" -v
Compiling MaskedFillTensorIntValueStaticModule_basic...
Running MaskedFillTensorIntValueStaticModule_basic...
FAIL - "MaskedFillTensorIntValueStaticModule_basic"

Unexpected outcome summary:

****** Failed tests - 1 tests
    FAIL - "MaskedFillTensorIntValueStaticModule_basic"
        @ trace item #0 - call to "forward"
        @ output of call to "forward"
        ERROR: value (Tensor with shape=[2, 3], dtype=torch.int64, min=+0.0, max=+9.0, mean=+4.167) is not close to golden value (Tensor with shape=[2, 3], dtype=torch.int64, min=+6.0, max=+9.0, mean=+6.5)


Summary:
    Failed: 1
➜  torch-mlir git:(masked_fill_tosa) ✗ python -m e2e_testing.main -c tosa -f "MaskedFillScalarIntValueStaticModule_basic" -v
Compiling MaskedFillScalarIntValueStaticModule_basic...
Running MaskedFillScalarIntValueStaticModule_basic...
FAIL - "MaskedFillScalarIntValueStaticModule_basic"

Unexpected outcome summary:

****** Failed tests - 1 tests
    FAIL - "MaskedFillScalarIntValueStaticModule_basic"
        @ trace item #0 - call to "forward"
        @ output of call to "forward"
        ERROR: value (Tensor with shape=[2, 3], dtype=torch.int64, min=+0.0, max=+9.0, mean=+4.0) is not close to golden value (Tensor with shape=[2, 3], dtype=torch.int64, min=+5.0, max=+9.0, mean=+5.667)


Summary:
    Failed: 1

```

**Comment by vivekkhandelwal1** [comment]
> Any idea to this kind of bug? Where is the golden value?
> 
> ```
> ➜  torch-mlir git:(masked_fill_tosa) ✗ python -m e2e_testing.main -c tosa -f "MaskedFillTensorIntValueStaticModule_basic" -v
> Compiling MaskedFillTensorIntValueStaticModule_basic...
> Running MaskedFillTensorIntValueStaticModule_basic...
> FAIL - "MaskedFillTensorIntValueStaticModule_basic"
> 
> Unexpected outcome summary:
> 
> ****** Failed tests - 1 tests
>     FAIL - "MaskedFillTensorIntValueStaticModule_basic"
>         @ trace item #0 - call to "forward"
>         @ output of call to "forward"
>         ERROR: value (Tensor with shape=[2, 3], dtype=torch.int64, min=+0.0, max=+9.0, mean=+4.167) is not close to golden value (Tensor with shape=[2, 3], dtype=torch.int64, min=+6.0, max=+9.0, mean=+6.5)
> 
> 
> Summary:
>     Failed: 1
> ➜  torch-mlir git:(masked_fill_tosa) ✗ python -m e2e_testing.main -c tosa -f "MaskedFillScalarIntValueStaticModule_basic" -v
> Compiling MaskedFillScalarIntValueStaticModule_basic...
> Running MaskedFillScalarIntValueStaticModule_basic...
> FAIL - "MaskedFillScalarIntValueStaticModule_basic"
> 
> Unexpected outcome summary:
> 
> ****** Failed tests - 1 tests
>     FAIL - "MaskedFillScalarIntValueStaticModule_basic"
>         @ trace item #0 - call to "forward"
>         @ output of call to "forward"
>         ERROR: value (Tensor with shape=[2, 3], dtype=torch.int64, min=+0.0, max=+9.0, mean=+4.0) is not close to golden value (Tensor with shape=[2, 3], dtype=torch.int64, min=+5.0, max=+9.0, mean=+5.667)
> 
> 
> Summary:
>     Failed: 1
> ```

This means that the `value` generated from TorchToTosa lowering is not equal to the `golden value` generated from `PyTorch`. It means there's an issue with the lowering itself.

**Comment by AmosLewis** [comment]
> > Any idea to this kind of bug? Where is the golden value?
> > ```
> > ➜  torch-mlir git:(masked_fill_tosa) ✗ python -m e2e_testing.main -c tosa -f "MaskedFillTensorIntValueStaticModule_basic" -v
> > Compiling MaskedFillTensorIntValueStaticModule_basic...
> > Running MaskedFillTensorIntValueStaticModule_basic...
> > FAIL - "MaskedFillTensorIntValueStaticModule_basic"
> > 
> > Unexpected outcome summary:
> > 
> > ****** Failed tests - 1 tests
> >     FAIL - "MaskedFillTensorIntValueStaticModule_basic"
> >         @ trace item #0 - call to "forward"
> >         @ output of call to "forward"
> >         ERROR: value (Tensor with shape=[2, 3], dtype=torch.int64, min=+0.0, max=+9.0, mean=+4.167) is not close to golden value (Tensor with shape=[2, 3], dtype=torch.int64, min=+6.0, max=+9.0, mean=+6.5)
> > 
> > 
> > Summary:
> >     Failed: 1
> > ➜  torch-mlir git:(masked_fill_tosa) ✗ python -m e2e_testing.main -c tosa -f "MaskedFillScalarIntValueStaticModule_basic" -v
> > Compiling MaskedFillScalarIntValueStaticModule_basic...
> > Running MaskedFillScalarIntValueStaticModule_basic...
> > FAIL - "MaskedFillScalarIntValueStaticModule_basic"
> > 
> > Unexpected outcome summary:
> > 
> > ****** Failed tests - 1 tests
> >     FAIL - "MaskedFillScalarIntValueStaticModule_basic"
> >         @ trace item #0 - call to "forward"
> >         @ output of call to "forward"
> >         ERROR: value (Tensor with shape=[2, 3], dtype=torch.int64, min=+0.0, max=+9.0, mean=+4.0) is not close to golden value (Tensor with shape=[2, 3], dtype=torch.int64, min=+5.0, max=+9.0, mean=+5.667)
> > 
> > 
> > Summary:
> >     Failed: 1
> > ```
> 
> This means that the `value` generated from TorchToTosa lowering is not equal to the `golden value` generated from `PyTorch`. It means there's an issue with the lowering itself.

Done

**Comment by vivekkhandelwal1** [comment]
Hi @AmosLewis, you need to add `MaskedFillTensorIntValueStaticModule_basic` to the LTC_XFAIL_SET

**Comment by AmosLewis** [comment]
> Hi @AmosLewis, you need to add `MaskedFillTensorIntValueStaticModule_basic` to the LTC_XFAIL_SET

Done

**Review by eric-k256 — APPROVED** [review]
TOSA changes look good.

**Review by ramiro050 — APPROVED** [review]

**Pull request merged**
