### PR TITLE
[MHLO] refactor pass configurations

### PR DESCRIPTION
**Pull request by fortianyou**
Related to https://github.com/llvm/torch-mlir/issues/1227

1. Reduce MHLO #ifdefs
2. Dismiss compilation warnings

### CODE REVIEW

**Review by Vremold — COMMENTED** [review]
Overall LGTM. Should we also configure `enableI32Index` and `enableStaticShape` in `torch-backend-to-mhlo-backend-pipeline`, which contains `convert-torch-to-mhlo` pass?

**Review by silvasean — APPROVED** [review]
Thanks!

**Comment by fortianyou** [comment]
> Overall LGTM. Could we add this feature to `torch-backend-to-mhlo-backend-pipeline` registered in `lib/Dialect/TorchConversion/Transforms/Passes.cpp`, too?

I have no idea if it's the right place to register in `lib/Dialect/TorchConversion/Transforms/Passes.cpp`. What do you think @silvasean @ZihengJiang

**Comment by silvasean** [comment]
> > Overall LGTM. Could we add this feature to `torch-backend-to-mhlo-backend-pipeline` registered in `lib/Dialect/TorchConversion/Transforms/Passes.cpp`, too?
> 
> I have no idea if it's the right place to register in `lib/Dialect/TorchConversion/Transforms/Passes.cpp`. What do you think @silvasean @ZihengJiang

We already have this registered there:

```
#ifdef TORCH_MLIR_ENABLE_MHLO
  mlir::PassPipelineRegistration<Torch::TorchLoweringPipelineOptions>(
      "torch-backend-to-mhlo-backend-pipeline",
      "Pipeline lowering torch backend contract to MHLO backend "
      "contract.",
      TorchConversion::createTorchBackendToMhloBackendPipeline);
#endif
```

You can replace `Torch::TorchLoweringPipelineOptions` with a new struct with options parallel to `def ConvertTorchToMhlo : Pass<"convert-torch-to-mhlo", "func::FuncOp"> {` (this is redundant but required in MLIR now).

**Review by ZihengJiang — APPROVED** [review]
Look good to me :)

**Comment by fortianyou** [comment]
Okk, @Vremold @silvasean I will split it into another PR.

**Pull request merged**
