### PR TITLE
[TORCH][MLIR] Add E2E support for `aten.reshape` op

### PR DESCRIPTION
**Pull request by Shukla-Gaurav**
This commit decomposes `aten.reshape` into `aten.view` op in the case of
value tensor type operand.

Signed-Off-by: Gaurav Shukla <gaurav@nod-labs.com>

### CODE REVIEW

**Review by ramiro050 — APPROVED** [review]
LGTM!

**Review by dan-garvey — APPROVED** [review]

**Comment by silvasean** [comment]
This is not a legal lowering.

https://pytorch.org/docs/stable/generated/torch.reshape.html

```
Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior.
```

So in some cases, it needs a deep copy rather than a view.

**Comment by silvasean** [comment]
I would suggest to add a test case covering the situations where reshaping must copy (e.g. when reshaping a view).

**Comment by Shukla-Gaurav** [comment]
> I would suggest to add a test case covering the situations where reshaping must copy (e.g. when reshaping a non-contiguous view).

How can I check for the non-contiguous case? @silvasean @ramiro050 @cathyzhyi

**Comment by cathyzhyi** [comment]
> I would suggest to add a test case covering the situations where reshaping must copy (e.g. when reshaping a non-contiguous view).

@silvasean I think we won't be able to check if the tensor is contiguous or not. We currently represent the contiguous, contiguous tensors the same way right?

**Comment by silvasean** [comment]
It won't be as easy as checking the type, but I think we can probably do something. Can you add the IR snippet of how this occurs in a real program?

**Comment by cathyzhyi** [comment]
> It won't be as easy as checking the type, but I think we can probably do something. Can you add the IR snippet of how this occurs in a real program?

In this snippet, %0 would have become discontiguous tensor in TorchScript.
```
func @forward(%arg0: !torch.vtensor<[?,?],f32>) -> !torch.vtensor<[6],f32> {
  %int6 = torch.constant.int 6
  %0 = torch.aten.t %arg0 : !torch.vtensor<[?,?],f32> -> !torch.vtensor<[?,?],f32>
  %1 = torch.prim.ListConstruct %int6 : (!torch.int) -> !torch.list<!torch.int>
  %2 = torch.aten.reshape %0, %1 : !torch.vtensor<[?,?],f32>, !torch.list<!torch.int> -> !torch.vtensor<[6],f32>
  return %2 : !torch.vtensor<[6],f32>
}
```

**Comment by silvasean** [comment]
Oh, I didn't realize this was happening with vtensor's :) In that case it's very easy! We can just lower it to `view` op on vtensor's.

**Comment by Shukla-Gaurav** [comment]
All the comments have been addressed now. @cathyzhyi @ramiro050 @silvasean Can I go ahead and merge this?

**Review by cathyzhyi — APPROVED** [review]
LGTM

**Comment by cathyzhyi** [comment]
@Shukla-Gaurav could you rebase and double check if tests are passing now? then you can go ahead and merge it.

**Pull request merged**
