### PR TITLE
Added tensorResultTypeAtIndex to  Patterns.h

### PR DESCRIPTION
**Pull request by afalkenberg1**
Need this for LayerNorm

### CODE REVIEW

**Comment by afalkenberg1** [comment]
I need this function for LayerNorm. I am going to split this up because this is of general use and not limited to LayerNorm only.

**Comment by afalkenberg1** [comment]
Hello @rsuderman  
please review. This is based on your feedback yesterday. 
Thanks.

**Review by rsuderman — APPROVED** [review]

**Comment by afalkenberg1** [comment]
Can this be merged please ? 
@stellaraccident @vivekkhandelwal1 @rsuderman

**Comment by vivekkhandelwal1** [comment]
> Can this be merged please ? @stellaraccident @vivekkhandelwal1 @rsuderman

Done

**Pull request merged**
