### PR TITLE
[MLIR][TORCH] Add heavydep tests for torch benchmarks

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
This commit adds e2e heavydep tests for the torch benchmarks.

Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

### CODE REVIEW

**Review by cathyzhyi — APPROVED** [review]
Looks good except the headers of both files need to be updated.
# A pretrained model to classify the input sentence.
# https://huggingface.co/philschmid/MiniLM-L6-H384-uncased-sst2

**Comment by cathyzhyi** [comment]
@vivekkhandelwal1 can you verify that the tests added can be generated correctly?

**Comment by vivekkhandelwal1** [comment]
> @vivekkhandelwal1 can you verify that the tests added can be generated correctly?

Do you mean to ask whether the tests run e2e and pass? All the tests don't pass. I have maintained the status of the tests here: https://docs.google.com/spreadsheets/d/15PcjKeHZIrB5LfDyuw7DGEEE8XnQEX2aX8lm8qbxV8A/edit#gid=1542003724

**Comment by cathyzhyi** [comment]
oh, I meant the `build_tools/torchscript_e2e_heavydep_tests/generate_serialized_tests.sh` can run successfully.

**Pull request merged**
