### PR TITLE
Add LTC architecture diagram

### PR DESCRIPTION
**Pull request by henrytwo**
Adds a high level architecture/dataflow diagram for LTC.

cc: @ke1337 @antoniojkim

### CODE REVIEW

**Comment by silvasean** [comment]
Do you have a PNG version? JPG is not good for diagrams.

LGTM otherwise.

**Comment by henrytwo** [comment]
@silvasean updated. Could I get some stamps please?

**Review by silvasean — APPROVED** [review]

**Comment by silvasean** [comment]
FYI, a "LGTM" is equivalent to the github "approved" button.

**Comment by henrytwo** [comment]
Sounds good, just wanted to be safe 😅

**Pull request merged**
