### PR TITLE
Add compile_commands.json to gitignore

### PR DESCRIPTION
**Pull request by Groverkss**

### CODE REVIEW

**Comment by Groverkss** [comment]
For neovim, generally clangd looks at the root of the directory for the compilation database.

Please let me know if there is an alternative workflow preferred!

**Comment by ramiro050** [comment]
I'm personally fine with these changes, but I'm not sure if there are any rules regarding adding things to the .gitignore. @silvasean PTAL

**Review by powderluv — APPROVED** [review]

**Comment by powderluv** [comment]
should be ok to add to .gitignore.

**Comment by silvasean** [comment]
seems fine

**Pull request merged**
