### PR TITLE
[MHLO] Init MHLO pooling-like op conversion

### PR DESCRIPTION
**Pull request by Vremold**
See RFC #999 

Co-authored-by: Bairen Yi <yibairen.byron@bytedance.com>
Co-authored-by: Jiawei Wu <xremold@gmail.com>
Co-authored-by: Tianyou Guo tianyou.gty@alibaba-inc.com
Co-authored-by: Xu Yan <yancey.yx@alibaba-inc.com>
Co-authored-by: Ziheng Jiang <ziheng.jiang@bytedance.com>

### CODE REVIEW

**Review by ZihengJiang — APPROVED** [review]
LGTM. Could you help remove the "*Op" suffix in the file names to align with TorchToLinalg convention?

**Comment by ZihengJiang** [comment]
Could you also add the file into the bazel build like this? https://github.com/llvm/torch-mlir/pull/1148

**Comment by Vremold** [comment]
> LGTM. Could you help remove the "*Op" suffix in the file names to align with TorchToLinalg convention?

Ok, done. Perhaps we can commit another PR to fix the rest unformatted filenames and tidy the codes after all these finished.

**Review by fortianyou — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
