### PR TITLE
Add E2E support for aten.warn

### PR DESCRIPTION
**Pull request by JakopinA**
Was wondering whether or not lowering makes any sense to have in this function?

### CODE REVIEW

**Comment by silvasean** [comment]
I don't think this makes sense in this form -- what model are you running that needs this?

**Comment by ramiro050** [comment]
> I don't think this makes sense in this form -- what model are you running that needs this?

I had added this op to the list of torchbench ops because it was being generated when importing `BERT_pytorch` into torch-mlir. However, I've just checked it again, and once the model gets to the maximize-value-semantics pass, the `warn` ops disappear from the graph. So this op might not be needed.

**Comment by silvasean** [comment]
Okay, that is what I would have expected -- these should be in code paths that end up folded away.

**Comment by vivekkhandelwal1** [comment]
> Okay, that is what I would have expected -- these should be in code paths that end up folded away. Same for is_grad_enabled.

And what about `prim.requires_grad`? @ramiro050 @silvasean

**Comment by silvasean** [comment]
prim.requires_grad would probably be similar to is_grad_enabled.

**Pull request closed without merging**
