### PR TITLE
lower torch.aten.isinf to linalg

### PR DESCRIPTION
**Pull request by renxida**

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
You need to add the test name to this list: https://github.com/llvm/torch-mlir/blob/6ddeb1a6efe7f61e80be3791952dc7c730dc1c72/projects/pt1/e2e_testing/xfail_sets.py#L1323
@renxida

**Review by stellaraccident — APPROVED** [review]
lgtm. needs conflicts resolved to land.

**Comment by stellaraccident** [comment]
Can you resolve conflicts and then we can land?

**Comment by renxida** [comment]
Encountering an error which I have no clue how to parse.

@rsuderman what's going on here?

```
Unexpected outcome summary: (lazy_tensor_core)

****** Failed tests - 1 tests
    FAIL - "ElementwiseAtenIsinfOpModule_basic"
        Runtime error: Traceback (most recent call last):
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/framework.py", line 302, in compile_and_run_test
            trace = config.run(compiled, golden_trace)
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/lazy_tensor_core.py", line 34, in run
            output = getattr(artifact, item.symbol)(*lazy_inputs)
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/test_suite/elementwise.py", line 3400, in forward
            return torch.ops.aten.isinf(x)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_ops.py", line 751, in __call__
            return self._op(*args, **(kwargs or {}))
        RuntimeError: Unimplemented Error: 
        	/main_checkout/torch-mlir/build/tools/torch-mlir/projects/ltc/csrc/base_lazy_backend/generated/shape_inference.cpp:35    std::vector<torch::lazy::Shape> torch::lazy::compute_shape_isinf(const at::Tensor &)
```

**Comment by renxida** [comment]
: / still same problem after cleaning up the commits. 

i cleaned up the commits, tried adding shapes to the test case. it still doesn't work.
```

Unexpected outcome summary: (lazy_tensor_core)

****** Failed tests - 1 tests
    FAIL - "ElementwiseAtenIsinfOpModule_basic"
        Runtime error: Traceback (most recent call last):
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/framework.py", line 302, in compile_and_run_test
            trace = config.run(compiled, golden_trace)
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/lazy_tensor_core.py", line 34, in run
            output = getattr(artifact, item.symbol)(*lazy_inputs)
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/test_suite/elementwise.py", line 3400, in forward
            return torch.ops.aten.isinf(x)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_ops.py", line 751, in __call__
            return self._op(*args, **(kwargs or {}))
        RuntimeError: Unimplemented Error: 
        	/main_checkout/torch-mlir/build/tools/torch-mlir/projects/ltc/csrc/base_lazy_backend/generated/shape_inference.cpp:35    std::vector<torch::lazy::Shape> torch::lazy::compute_shape_isinf(const at::Tensor &)


Summary:
    Passed: 965
    Failed: 1
    Expectedly Failed: 126
···

**Pull request merged**
