### PR TITLE
Enhance PyTorch C++ ABI compatibility checking

### PR DESCRIPTION
**Pull request by rdadolf**
Compiling torch-mlir against a source version of PyTorch or an official wheel compiled with the new C++ stdlib ABI fails, as torch-mlir doesn't know how to set compiler flags to remain compatible. This changes the way torch-mlir looks at PyTorch and tries to more closely match the ABI settings, regardless of whether it's the common official wheel or some other version.

Tagging @stellaraccident due to your work on #138.

### CODE REVIEW

**Comment by powderluv** [comment]
Thanks for your contribution @rdadolf 

Is there any reason we want to support the non -D_GLIBCXX_USE_CXX11_ABI= flow? Could we just simply depend on the the version using CXX11 ABI ?

**Comment by rdadolf** [comment]
> Thanks for your contribution @rdadolf
> 
> Is there any reason we want to support the non -D_GLIBCXX_USE_CXX11_ABI= flow? Could we just simply depend on the the version using CXX11 ABI ?

PyTorch uses the old ABI by default, so if you `pip install` it, you'll get a binary that was compiled with `_GLIBCXX_USE_CXX11=0`. My understanding is that this is due to the age of manylinux, which stretches back to include a gcc version that didn't have the new C++ standard library capability. Since manylinux is required by pypa, PyTorch is forced to use the old one. This is actually an [ongoing issue with PyTorch](https://github.com/pytorch/pytorch/issues/17492).

The C++ ABI compatibility version flag (1011, 1013, etc.) is separate from that.

**Comment by stellaraccident** [comment]
Thanks for digging into this. If you ever see a way to improve this and not rely on the old way, we are just doing our best to match PT and broad Linux compatibility -- and there are no strong preferences beyond that. I look forward to us being firmly in the modern era on this but the last I evaluated the interlocking pieces, I guess we may be still a year or two out :/

**Comment by rdadolf** [comment]
I did also look into the status of the Torch machinery (as you mentioned in those comments), but PyTorch explicitly doesn't support clang on Linux (and are aggressive about checking for it, e.g.: https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L267). It's possible to force the issue and bypass the check, but we'd still need to generate our own flags for clang, which would leave us more or less back with the current approach. Using `torch.utils.cpp_extension` for gcc compilers and our own thing for clang compilers seems pretty sub-optimal.

if the PyTorch folks decide to expand support, we could revisit the issue. Hence it seemed reasonable to leave your original comments about the future in---they still apply in pretty much the same way as before.

**Comment by stellaraccident** [comment]
Yeah - I think the clang on Linux bit only comes for development: for real builds, we use system compilers (gcc). I'm pretty sketched out in general about deviating because when these things break, it is super subtle and a support nightmare. Personally, I always prefer aligning to whatever upstream convention is in play.

**Pull request merged**
